// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

// Protobuf Java Version: 3.25.1
package dev.zanderp.opencfmoto.aa.proto;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code dev.zanderp.opencfmoto.aa.proto.MessageStatus}
   */
  public enum MessageStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STATUS_SUCCESS = 0;</code>
     */
    STATUS_SUCCESS(0),
    /**
     * <code>STATUS_UNSOLICITED_MESSAGE = 1;</code>
     */
    STATUS_UNSOLICITED_MESSAGE(1),
    /**
     * <code>STATUS_NO_COMPATIBLE_VERSION = -1;</code>
     */
    STATUS_NO_COMPATIBLE_VERSION(-1),
    /**
     * <code>STATUS_CERTIFICATE_ERROR = -2;</code>
     */
    STATUS_CERTIFICATE_ERROR(-2),
    /**
     * <code>STATUS_AUTHENTICATION_FAILURE = -3;</code>
     */
    STATUS_AUTHENTICATION_FAILURE(-3),
    /**
     * <code>STATUS_INVALID_SERVICE = -4;</code>
     */
    STATUS_INVALID_SERVICE(-4),
    /**
     * <code>STATUS_INVALID_CHANNEL = -5;</code>
     */
    STATUS_INVALID_CHANNEL(-5),
    /**
     * <code>STATUS_INVALID_PRIORITY = -6;</code>
     */
    STATUS_INVALID_PRIORITY(-6),
    /**
     * <code>STATUS_INTERNAL_ERROR = -7;</code>
     */
    STATUS_INTERNAL_ERROR(-7),
    /**
     * <code>STATUS_MEDIA_CONFIG_MISMATCH = -8;</code>
     */
    STATUS_MEDIA_CONFIG_MISMATCH(-8),
    /**
     * <code>STATUS_INVALID_SENSOR = -9;</code>
     */
    STATUS_INVALID_SENSOR(-9),
    /**
     * <code>STATUS_BLUETOOTH_PAIRING_DELAYED = -10;</code>
     */
    STATUS_BLUETOOTH_PAIRING_DELAYED(-10),
    /**
     * <code>STATUS_BLUETOOTH_UNAVAILABLE = -11;</code>
     */
    STATUS_BLUETOOTH_UNAVAILABLE(-11),
    /**
     * <code>STATUS_BLUETOOTH_INVALID_ADDRESS = -12;</code>
     */
    STATUS_BLUETOOTH_INVALID_ADDRESS(-12),
    /**
     * <code>STATUS_BLUETOOTH_INVALID_PAIRING_METHOD = -13;</code>
     */
    STATUS_BLUETOOTH_INVALID_PAIRING_METHOD(-13),
    /**
     * <code>STATUS_BLUETOOTH_INVALID_AUTH_DATA = -14;</code>
     */
    STATUS_BLUETOOTH_INVALID_AUTH_DATA(-14),
    /**
     * <code>STATUS_BLUETOOTH_AUTH_DATA_MISMATCH = -15;</code>
     */
    STATUS_BLUETOOTH_AUTH_DATA_MISMATCH(-15),
    /**
     * <code>STATUS_BLUETOOTH_HFP_ANOTHER_CONNECTION = -16;</code>
     */
    STATUS_BLUETOOTH_HFP_ANOTHER_CONNECTION(-16),
    /**
     * <code>STATUS_BLUETOOTH_HFP_CONNECTION_FAILURE = -17;</code>
     */
    STATUS_BLUETOOTH_HFP_CONNECTION_FAILURE(-17),
    /**
     * <code>STATUS_KEYCODE_NOT_BOUND = -18;</code>
     */
    STATUS_KEYCODE_NOT_BOUND(-18),
    /**
     * <code>STATUS_RADIO_INVALID_STATION = -19;</code>
     */
    STATUS_RADIO_INVALID_STATION(-19),
    /**
     * <code>STATUS_INVALID_INPUT = -20;</code>
     */
    STATUS_INVALID_INPUT(-20),
    /**
     * <code>STATUS_RADIO_STATION_PRESETS_NOT_SUPPORTED = -21;</code>
     */
    STATUS_RADIO_STATION_PRESETS_NOT_SUPPORTED(-21),
    /**
     * <code>STATUS_RADIO_COMM_ERROR = -22;</code>
     */
    STATUS_RADIO_COMM_ERROR(-22),
    /**
     * <code>STATUS_AUTHENTICATION_FAILURE_CERT_NOT_YET_VALID = -23;</code>
     */
    STATUS_AUTHENTICATION_FAILURE_CERT_NOT_YET_VALID(-23),
    /**
     * <code>STATUS_AUTHENTICATION_FAILURE_CERT_EXPIRED = -24;</code>
     */
    STATUS_AUTHENTICATION_FAILURE_CERT_EXPIRED(-24),
    /**
     * <code>STATUS_PING_TIMEOUT = -25;</code>
     */
    STATUS_PING_TIMEOUT(-25),
    /**
     * <code>STATUS_COMMAND_NOT_SUPPORTED = -250;</code>
     */
    STATUS_COMMAND_NOT_SUPPORTED(-250),
    /**
     * <code>STATUS_FRAMING_ERROR = -251;</code>
     */
    STATUS_FRAMING_ERROR(-251),
    /**
     * <code>STATUS_UNEXPECTED_MESSAGE = -253;</code>
     */
    STATUS_UNEXPECTED_MESSAGE(-253),
    /**
     * <code>STATUS_BUSY = -254;</code>
     */
    STATUS_BUSY(-254),
    /**
     * <code>STATUS_OUT_OF_MEMORY = -255;</code>
     */
    STATUS_OUT_OF_MEMORY(-255),
    ;

    /**
     * <code>STATUS_SUCCESS = 0;</code>
     */
    public static final int STATUS_SUCCESS_VALUE = 0;
    /**
     * <code>STATUS_UNSOLICITED_MESSAGE = 1;</code>
     */
    public static final int STATUS_UNSOLICITED_MESSAGE_VALUE = 1;
    /**
     * <code>STATUS_NO_COMPATIBLE_VERSION = -1;</code>
     */
    public static final int STATUS_NO_COMPATIBLE_VERSION_VALUE = -1;
    /**
     * <code>STATUS_CERTIFICATE_ERROR = -2;</code>
     */
    public static final int STATUS_CERTIFICATE_ERROR_VALUE = -2;
    /**
     * <code>STATUS_AUTHENTICATION_FAILURE = -3;</code>
     */
    public static final int STATUS_AUTHENTICATION_FAILURE_VALUE = -3;
    /**
     * <code>STATUS_INVALID_SERVICE = -4;</code>
     */
    public static final int STATUS_INVALID_SERVICE_VALUE = -4;
    /**
     * <code>STATUS_INVALID_CHANNEL = -5;</code>
     */
    public static final int STATUS_INVALID_CHANNEL_VALUE = -5;
    /**
     * <code>STATUS_INVALID_PRIORITY = -6;</code>
     */
    public static final int STATUS_INVALID_PRIORITY_VALUE = -6;
    /**
     * <code>STATUS_INTERNAL_ERROR = -7;</code>
     */
    public static final int STATUS_INTERNAL_ERROR_VALUE = -7;
    /**
     * <code>STATUS_MEDIA_CONFIG_MISMATCH = -8;</code>
     */
    public static final int STATUS_MEDIA_CONFIG_MISMATCH_VALUE = -8;
    /**
     * <code>STATUS_INVALID_SENSOR = -9;</code>
     */
    public static final int STATUS_INVALID_SENSOR_VALUE = -9;
    /**
     * <code>STATUS_BLUETOOTH_PAIRING_DELAYED = -10;</code>
     */
    public static final int STATUS_BLUETOOTH_PAIRING_DELAYED_VALUE = -10;
    /**
     * <code>STATUS_BLUETOOTH_UNAVAILABLE = -11;</code>
     */
    public static final int STATUS_BLUETOOTH_UNAVAILABLE_VALUE = -11;
    /**
     * <code>STATUS_BLUETOOTH_INVALID_ADDRESS = -12;</code>
     */
    public static final int STATUS_BLUETOOTH_INVALID_ADDRESS_VALUE = -12;
    /**
     * <code>STATUS_BLUETOOTH_INVALID_PAIRING_METHOD = -13;</code>
     */
    public static final int STATUS_BLUETOOTH_INVALID_PAIRING_METHOD_VALUE = -13;
    /**
     * <code>STATUS_BLUETOOTH_INVALID_AUTH_DATA = -14;</code>
     */
    public static final int STATUS_BLUETOOTH_INVALID_AUTH_DATA_VALUE = -14;
    /**
     * <code>STATUS_BLUETOOTH_AUTH_DATA_MISMATCH = -15;</code>
     */
    public static final int STATUS_BLUETOOTH_AUTH_DATA_MISMATCH_VALUE = -15;
    /**
     * <code>STATUS_BLUETOOTH_HFP_ANOTHER_CONNECTION = -16;</code>
     */
    public static final int STATUS_BLUETOOTH_HFP_ANOTHER_CONNECTION_VALUE = -16;
    /**
     * <code>STATUS_BLUETOOTH_HFP_CONNECTION_FAILURE = -17;</code>
     */
    public static final int STATUS_BLUETOOTH_HFP_CONNECTION_FAILURE_VALUE = -17;
    /**
     * <code>STATUS_KEYCODE_NOT_BOUND = -18;</code>
     */
    public static final int STATUS_KEYCODE_NOT_BOUND_VALUE = -18;
    /**
     * <code>STATUS_RADIO_INVALID_STATION = -19;</code>
     */
    public static final int STATUS_RADIO_INVALID_STATION_VALUE = -19;
    /**
     * <code>STATUS_INVALID_INPUT = -20;</code>
     */
    public static final int STATUS_INVALID_INPUT_VALUE = -20;
    /**
     * <code>STATUS_RADIO_STATION_PRESETS_NOT_SUPPORTED = -21;</code>
     */
    public static final int STATUS_RADIO_STATION_PRESETS_NOT_SUPPORTED_VALUE = -21;
    /**
     * <code>STATUS_RADIO_COMM_ERROR = -22;</code>
     */
    public static final int STATUS_RADIO_COMM_ERROR_VALUE = -22;
    /**
     * <code>STATUS_AUTHENTICATION_FAILURE_CERT_NOT_YET_VALID = -23;</code>
     */
    public static final int STATUS_AUTHENTICATION_FAILURE_CERT_NOT_YET_VALID_VALUE = -23;
    /**
     * <code>STATUS_AUTHENTICATION_FAILURE_CERT_EXPIRED = -24;</code>
     */
    public static final int STATUS_AUTHENTICATION_FAILURE_CERT_EXPIRED_VALUE = -24;
    /**
     * <code>STATUS_PING_TIMEOUT = -25;</code>
     */
    public static final int STATUS_PING_TIMEOUT_VALUE = -25;
    /**
     * <code>STATUS_COMMAND_NOT_SUPPORTED = -250;</code>
     */
    public static final int STATUS_COMMAND_NOT_SUPPORTED_VALUE = -250;
    /**
     * <code>STATUS_FRAMING_ERROR = -251;</code>
     */
    public static final int STATUS_FRAMING_ERROR_VALUE = -251;
    /**
     * <code>STATUS_UNEXPECTED_MESSAGE = -253;</code>
     */
    public static final int STATUS_UNEXPECTED_MESSAGE_VALUE = -253;
    /**
     * <code>STATUS_BUSY = -254;</code>
     */
    public static final int STATUS_BUSY_VALUE = -254;
    /**
     * <code>STATUS_OUT_OF_MEMORY = -255;</code>
     */
    public static final int STATUS_OUT_OF_MEMORY_VALUE = -255;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageStatus forNumber(int value) {
      switch (value) {
        case 0: return STATUS_SUCCESS;
        case 1: return STATUS_UNSOLICITED_MESSAGE;
        case -1: return STATUS_NO_COMPATIBLE_VERSION;
        case -2: return STATUS_CERTIFICATE_ERROR;
        case -3: return STATUS_AUTHENTICATION_FAILURE;
        case -4: return STATUS_INVALID_SERVICE;
        case -5: return STATUS_INVALID_CHANNEL;
        case -6: return STATUS_INVALID_PRIORITY;
        case -7: return STATUS_INTERNAL_ERROR;
        case -8: return STATUS_MEDIA_CONFIG_MISMATCH;
        case -9: return STATUS_INVALID_SENSOR;
        case -10: return STATUS_BLUETOOTH_PAIRING_DELAYED;
        case -11: return STATUS_BLUETOOTH_UNAVAILABLE;
        case -12: return STATUS_BLUETOOTH_INVALID_ADDRESS;
        case -13: return STATUS_BLUETOOTH_INVALID_PAIRING_METHOD;
        case -14: return STATUS_BLUETOOTH_INVALID_AUTH_DATA;
        case -15: return STATUS_BLUETOOTH_AUTH_DATA_MISMATCH;
        case -16: return STATUS_BLUETOOTH_HFP_ANOTHER_CONNECTION;
        case -17: return STATUS_BLUETOOTH_HFP_CONNECTION_FAILURE;
        case -18: return STATUS_KEYCODE_NOT_BOUND;
        case -19: return STATUS_RADIO_INVALID_STATION;
        case -20: return STATUS_INVALID_INPUT;
        case -21: return STATUS_RADIO_STATION_PRESETS_NOT_SUPPORTED;
        case -22: return STATUS_RADIO_COMM_ERROR;
        case -23: return STATUS_AUTHENTICATION_FAILURE_CERT_NOT_YET_VALID;
        case -24: return STATUS_AUTHENTICATION_FAILURE_CERT_EXPIRED;
        case -25: return STATUS_PING_TIMEOUT;
        case -250: return STATUS_COMMAND_NOT_SUPPORTED;
        case -251: return STATUS_FRAMING_ERROR;
        case -253: return STATUS_UNEXPECTED_MESSAGE;
        case -254: return STATUS_BUSY;
        case -255: return STATUS_OUT_OF_MEMORY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageStatus>() {
            public MessageStatus findValueByNumber(int number) {
              return MessageStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return dev.zanderp.opencfmoto.aa.proto.Common.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageStatus[] VALUES = values();

    public static MessageStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:dev.zanderp.opencfmoto.aa.proto.MessageStatus)
  }

  public interface HeadUnitInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dev.zanderp.opencfmoto.aa.proto.HeadUnitInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string head_unit_make = 1;</code>
     * @return Whether the headUnitMake field is set.
     */
    boolean hasHeadUnitMake();
    /**
     * <code>optional string head_unit_make = 1;</code>
     * @return The headUnitMake.
     */
    java.lang.String getHeadUnitMake();
    /**
     * <code>optional string head_unit_make = 1;</code>
     * @return The bytes for headUnitMake.
     */
    com.google.protobuf.ByteString
        getHeadUnitMakeBytes();

    /**
     * <code>optional string head_unit_model = 2;</code>
     * @return Whether the headUnitModel field is set.
     */
    boolean hasHeadUnitModel();
    /**
     * <code>optional string head_unit_model = 2;</code>
     * @return The headUnitModel.
     */
    java.lang.String getHeadUnitModel();
    /**
     * <code>optional string head_unit_model = 2;</code>
     * @return The bytes for headUnitModel.
     */
    com.google.protobuf.ByteString
        getHeadUnitModelBytes();

    /**
     * <code>optional string make = 3;</code>
     * @return Whether the make field is set.
     */
    boolean hasMake();
    /**
     * <code>optional string make = 3;</code>
     * @return The make.
     */
    java.lang.String getMake();
    /**
     * <code>optional string make = 3;</code>
     * @return The bytes for make.
     */
    com.google.protobuf.ByteString
        getMakeBytes();

    /**
     * <code>optional string model = 4;</code>
     * @return Whether the model field is set.
     */
    boolean hasModel();
    /**
     * <code>optional string model = 4;</code>
     * @return The model.
     */
    java.lang.String getModel();
    /**
     * <code>optional string model = 4;</code>
     * @return The bytes for model.
     */
    com.google.protobuf.ByteString
        getModelBytes();

    /**
     * <code>optional string year = 5;</code>
     * @return Whether the year field is set.
     */
    boolean hasYear();
    /**
     * <code>optional string year = 5;</code>
     * @return The year.
     */
    java.lang.String getYear();
    /**
     * <code>optional string year = 5;</code>
     * @return The bytes for year.
     */
    com.google.protobuf.ByteString
        getYearBytes();

    /**
     * <code>optional string head_unit_software_build = 6;</code>
     * @return Whether the headUnitSoftwareBuild field is set.
     */
    boolean hasHeadUnitSoftwareBuild();
    /**
     * <code>optional string head_unit_software_build = 6;</code>
     * @return The headUnitSoftwareBuild.
     */
    java.lang.String getHeadUnitSoftwareBuild();
    /**
     * <code>optional string head_unit_software_build = 6;</code>
     * @return The bytes for headUnitSoftwareBuild.
     */
    com.google.protobuf.ByteString
        getHeadUnitSoftwareBuildBytes();

    /**
     * <code>optional string vehicle_id = 7;</code>
     * @return Whether the vehicleId field is set.
     */
    boolean hasVehicleId();
    /**
     * <code>optional string vehicle_id = 7;</code>
     * @return The vehicleId.
     */
    java.lang.String getVehicleId();
    /**
     * <code>optional string vehicle_id = 7;</code>
     * @return The bytes for vehicleId.
     */
    com.google.protobuf.ByteString
        getVehicleIdBytes();

    /**
     * <code>optional string head_unit_software_version = 8;</code>
     * @return Whether the headUnitSoftwareVersion field is set.
     */
    boolean hasHeadUnitSoftwareVersion();
    /**
     * <code>optional string head_unit_software_version = 8;</code>
     * @return The headUnitSoftwareVersion.
     */
    java.lang.String getHeadUnitSoftwareVersion();
    /**
     * <code>optional string head_unit_software_version = 8;</code>
     * @return The bytes for headUnitSoftwareVersion.
     */
    com.google.protobuf.ByteString
        getHeadUnitSoftwareVersionBytes();
  }
  /**
   * Protobuf type {@code dev.zanderp.opencfmoto.aa.proto.HeadUnitInfo}
   */
  public static final class HeadUnitInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dev.zanderp.opencfmoto.aa.proto.HeadUnitInfo)
      HeadUnitInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HeadUnitInfo.newBuilder() to construct.
    private HeadUnitInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HeadUnitInfo() {
      headUnitMake_ = "";
      headUnitModel_ = "";
      make_ = "";
      model_ = "";
      year_ = "";
      headUnitSoftwareBuild_ = "";
      vehicleId_ = "";
      headUnitSoftwareVersion_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HeadUnitInfo();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.zanderp.opencfmoto.aa.proto.Common.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_HeadUnitInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.zanderp.opencfmoto.aa.proto.Common.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_HeadUnitInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo.class, dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo.Builder.class);
    }

    private int bitField0_;
    public static final int HEAD_UNIT_MAKE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object headUnitMake_ = "";
    /**
     * <code>optional string head_unit_make = 1;</code>
     * @return Whether the headUnitMake field is set.
     */
    @java.lang.Override
    public boolean hasHeadUnitMake() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string head_unit_make = 1;</code>
     * @return The headUnitMake.
     */
    @java.lang.Override
    public java.lang.String getHeadUnitMake() {
      java.lang.Object ref = headUnitMake_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          headUnitMake_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string head_unit_make = 1;</code>
     * @return The bytes for headUnitMake.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHeadUnitMakeBytes() {
      java.lang.Object ref = headUnitMake_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headUnitMake_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEAD_UNIT_MODEL_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object headUnitModel_ = "";
    /**
     * <code>optional string head_unit_model = 2;</code>
     * @return Whether the headUnitModel field is set.
     */
    @java.lang.Override
    public boolean hasHeadUnitModel() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string head_unit_model = 2;</code>
     * @return The headUnitModel.
     */
    @java.lang.Override
    public java.lang.String getHeadUnitModel() {
      java.lang.Object ref = headUnitModel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          headUnitModel_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string head_unit_model = 2;</code>
     * @return The bytes for headUnitModel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHeadUnitModelBytes() {
      java.lang.Object ref = headUnitModel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headUnitModel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAKE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object make_ = "";
    /**
     * <code>optional string make = 3;</code>
     * @return Whether the make field is set.
     */
    @java.lang.Override
    public boolean hasMake() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string make = 3;</code>
     * @return The make.
     */
    @java.lang.Override
    public java.lang.String getMake() {
      java.lang.Object ref = make_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          make_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string make = 3;</code>
     * @return The bytes for make.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMakeBytes() {
      java.lang.Object ref = make_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        make_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODEL_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object model_ = "";
    /**
     * <code>optional string model = 4;</code>
     * @return Whether the model field is set.
     */
    @java.lang.Override
    public boolean hasModel() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string model = 4;</code>
     * @return The model.
     */
    @java.lang.Override
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          model_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string model = 4;</code>
     * @return The bytes for model.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int YEAR_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object year_ = "";
    /**
     * <code>optional string year = 5;</code>
     * @return Whether the year field is set.
     */
    @java.lang.Override
    public boolean hasYear() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string year = 5;</code>
     * @return The year.
     */
    @java.lang.Override
    public java.lang.String getYear() {
      java.lang.Object ref = year_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          year_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string year = 5;</code>
     * @return The bytes for year.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getYearBytes() {
      java.lang.Object ref = year_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        year_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEAD_UNIT_SOFTWARE_BUILD_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object headUnitSoftwareBuild_ = "";
    /**
     * <code>optional string head_unit_software_build = 6;</code>
     * @return Whether the headUnitSoftwareBuild field is set.
     */
    @java.lang.Override
    public boolean hasHeadUnitSoftwareBuild() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string head_unit_software_build = 6;</code>
     * @return The headUnitSoftwareBuild.
     */
    @java.lang.Override
    public java.lang.String getHeadUnitSoftwareBuild() {
      java.lang.Object ref = headUnitSoftwareBuild_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          headUnitSoftwareBuild_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string head_unit_software_build = 6;</code>
     * @return The bytes for headUnitSoftwareBuild.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHeadUnitSoftwareBuildBytes() {
      java.lang.Object ref = headUnitSoftwareBuild_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headUnitSoftwareBuild_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VEHICLE_ID_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object vehicleId_ = "";
    /**
     * <code>optional string vehicle_id = 7;</code>
     * @return Whether the vehicleId field is set.
     */
    @java.lang.Override
    public boolean hasVehicleId() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string vehicle_id = 7;</code>
     * @return The vehicleId.
     */
    @java.lang.Override
    public java.lang.String getVehicleId() {
      java.lang.Object ref = vehicleId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          vehicleId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string vehicle_id = 7;</code>
     * @return The bytes for vehicleId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getVehicleIdBytes() {
      java.lang.Object ref = vehicleId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vehicleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEAD_UNIT_SOFTWARE_VERSION_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private volatile java.lang.Object headUnitSoftwareVersion_ = "";
    /**
     * <code>optional string head_unit_software_version = 8;</code>
     * @return Whether the headUnitSoftwareVersion field is set.
     */
    @java.lang.Override
    public boolean hasHeadUnitSoftwareVersion() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional string head_unit_software_version = 8;</code>
     * @return The headUnitSoftwareVersion.
     */
    @java.lang.Override
    public java.lang.String getHeadUnitSoftwareVersion() {
      java.lang.Object ref = headUnitSoftwareVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          headUnitSoftwareVersion_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string head_unit_software_version = 8;</code>
     * @return The bytes for headUnitSoftwareVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHeadUnitSoftwareVersionBytes() {
      java.lang.Object ref = headUnitSoftwareVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headUnitSoftwareVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, headUnitMake_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, headUnitModel_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, make_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, model_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, year_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, headUnitSoftwareBuild_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, vehicleId_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, headUnitSoftwareVersion_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, headUnitMake_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, headUnitModel_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, make_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, model_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, year_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, headUnitSoftwareBuild_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, vehicleId_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, headUnitSoftwareVersion_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo)) {
        return super.equals(obj);
      }
      dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo other = (dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo) obj;

      if (hasHeadUnitMake() != other.hasHeadUnitMake()) return false;
      if (hasHeadUnitMake()) {
        if (!getHeadUnitMake()
            .equals(other.getHeadUnitMake())) return false;
      }
      if (hasHeadUnitModel() != other.hasHeadUnitModel()) return false;
      if (hasHeadUnitModel()) {
        if (!getHeadUnitModel()
            .equals(other.getHeadUnitModel())) return false;
      }
      if (hasMake() != other.hasMake()) return false;
      if (hasMake()) {
        if (!getMake()
            .equals(other.getMake())) return false;
      }
      if (hasModel() != other.hasModel()) return false;
      if (hasModel()) {
        if (!getModel()
            .equals(other.getModel())) return false;
      }
      if (hasYear() != other.hasYear()) return false;
      if (hasYear()) {
        if (!getYear()
            .equals(other.getYear())) return false;
      }
      if (hasHeadUnitSoftwareBuild() != other.hasHeadUnitSoftwareBuild()) return false;
      if (hasHeadUnitSoftwareBuild()) {
        if (!getHeadUnitSoftwareBuild()
            .equals(other.getHeadUnitSoftwareBuild())) return false;
      }
      if (hasVehicleId() != other.hasVehicleId()) return false;
      if (hasVehicleId()) {
        if (!getVehicleId()
            .equals(other.getVehicleId())) return false;
      }
      if (hasHeadUnitSoftwareVersion() != other.hasHeadUnitSoftwareVersion()) return false;
      if (hasHeadUnitSoftwareVersion()) {
        if (!getHeadUnitSoftwareVersion()
            .equals(other.getHeadUnitSoftwareVersion())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeadUnitMake()) {
        hash = (37 * hash) + HEAD_UNIT_MAKE_FIELD_NUMBER;
        hash = (53 * hash) + getHeadUnitMake().hashCode();
      }
      if (hasHeadUnitModel()) {
        hash = (37 * hash) + HEAD_UNIT_MODEL_FIELD_NUMBER;
        hash = (53 * hash) + getHeadUnitModel().hashCode();
      }
      if (hasMake()) {
        hash = (37 * hash) + MAKE_FIELD_NUMBER;
        hash = (53 * hash) + getMake().hashCode();
      }
      if (hasModel()) {
        hash = (37 * hash) + MODEL_FIELD_NUMBER;
        hash = (53 * hash) + getModel().hashCode();
      }
      if (hasYear()) {
        hash = (37 * hash) + YEAR_FIELD_NUMBER;
        hash = (53 * hash) + getYear().hashCode();
      }
      if (hasHeadUnitSoftwareBuild()) {
        hash = (37 * hash) + HEAD_UNIT_SOFTWARE_BUILD_FIELD_NUMBER;
        hash = (53 * hash) + getHeadUnitSoftwareBuild().hashCode();
      }
      if (hasVehicleId()) {
        hash = (37 * hash) + VEHICLE_ID_FIELD_NUMBER;
        hash = (53 * hash) + getVehicleId().hashCode();
      }
      if (hasHeadUnitSoftwareVersion()) {
        hash = (37 * hash) + HEAD_UNIT_SOFTWARE_VERSION_FIELD_NUMBER;
        hash = (53 * hash) + getHeadUnitSoftwareVersion().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dev.zanderp.opencfmoto.aa.proto.HeadUnitInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dev.zanderp.opencfmoto.aa.proto.HeadUnitInfo)
        dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.zanderp.opencfmoto.aa.proto.Common.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_HeadUnitInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.zanderp.opencfmoto.aa.proto.Common.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_HeadUnitInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo.class, dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo.Builder.class);
      }

      // Construct using dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        headUnitMake_ = "";
        headUnitModel_ = "";
        make_ = "";
        model_ = "";
        year_ = "";
        headUnitSoftwareBuild_ = "";
        vehicleId_ = "";
        headUnitSoftwareVersion_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.zanderp.opencfmoto.aa.proto.Common.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_HeadUnitInfo_descriptor;
      }

      @java.lang.Override
      public dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo getDefaultInstanceForType() {
        return dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo.getDefaultInstance();
      }

      @java.lang.Override
      public dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo build() {
        dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo buildPartial() {
        dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo result = new dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.headUnitMake_ = headUnitMake_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.headUnitModel_ = headUnitModel_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.make_ = make_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.model_ = model_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.year_ = year_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.headUnitSoftwareBuild_ = headUnitSoftwareBuild_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.vehicleId_ = vehicleId_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.headUnitSoftwareVersion_ = headUnitSoftwareVersion_;
          to_bitField0_ |= 0x00000080;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo) {
          return mergeFrom((dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo other) {
        if (other == dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo.getDefaultInstance()) return this;
        if (other.hasHeadUnitMake()) {
          headUnitMake_ = other.headUnitMake_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasHeadUnitModel()) {
          headUnitModel_ = other.headUnitModel_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasMake()) {
          make_ = other.make_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasModel()) {
          model_ = other.model_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasYear()) {
          year_ = other.year_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.hasHeadUnitSoftwareBuild()) {
          headUnitSoftwareBuild_ = other.headUnitSoftwareBuild_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.hasVehicleId()) {
          vehicleId_ = other.vehicleId_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (other.hasHeadUnitSoftwareVersion()) {
          headUnitSoftwareVersion_ = other.headUnitSoftwareVersion_;
          bitField0_ |= 0x00000080;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                headUnitMake_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                headUnitModel_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                make_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                model_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                year_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                headUnitSoftwareBuild_ = input.readBytes();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                vehicleId_ = input.readBytes();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 66: {
                headUnitSoftwareVersion_ = input.readBytes();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object headUnitMake_ = "";
      /**
       * <code>optional string head_unit_make = 1;</code>
       * @return Whether the headUnitMake field is set.
       */
      public boolean hasHeadUnitMake() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string head_unit_make = 1;</code>
       * @return The headUnitMake.
       */
      public java.lang.String getHeadUnitMake() {
        java.lang.Object ref = headUnitMake_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            headUnitMake_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string head_unit_make = 1;</code>
       * @return The bytes for headUnitMake.
       */
      public com.google.protobuf.ByteString
          getHeadUnitMakeBytes() {
        java.lang.Object ref = headUnitMake_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headUnitMake_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string head_unit_make = 1;</code>
       * @param value The headUnitMake to set.
       * @return This builder for chaining.
       */
      public Builder setHeadUnitMake(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        headUnitMake_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string head_unit_make = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeadUnitMake() {
        headUnitMake_ = getDefaultInstance().getHeadUnitMake();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string head_unit_make = 1;</code>
       * @param value The bytes for headUnitMake to set.
       * @return This builder for chaining.
       */
      public Builder setHeadUnitMakeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        headUnitMake_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object headUnitModel_ = "";
      /**
       * <code>optional string head_unit_model = 2;</code>
       * @return Whether the headUnitModel field is set.
       */
      public boolean hasHeadUnitModel() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string head_unit_model = 2;</code>
       * @return The headUnitModel.
       */
      public java.lang.String getHeadUnitModel() {
        java.lang.Object ref = headUnitModel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            headUnitModel_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string head_unit_model = 2;</code>
       * @return The bytes for headUnitModel.
       */
      public com.google.protobuf.ByteString
          getHeadUnitModelBytes() {
        java.lang.Object ref = headUnitModel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headUnitModel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string head_unit_model = 2;</code>
       * @param value The headUnitModel to set.
       * @return This builder for chaining.
       */
      public Builder setHeadUnitModel(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        headUnitModel_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string head_unit_model = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeadUnitModel() {
        headUnitModel_ = getDefaultInstance().getHeadUnitModel();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string head_unit_model = 2;</code>
       * @param value The bytes for headUnitModel to set.
       * @return This builder for chaining.
       */
      public Builder setHeadUnitModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        headUnitModel_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object make_ = "";
      /**
       * <code>optional string make = 3;</code>
       * @return Whether the make field is set.
       */
      public boolean hasMake() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string make = 3;</code>
       * @return The make.
       */
      public java.lang.String getMake() {
        java.lang.Object ref = make_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            make_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string make = 3;</code>
       * @return The bytes for make.
       */
      public com.google.protobuf.ByteString
          getMakeBytes() {
        java.lang.Object ref = make_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          make_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string make = 3;</code>
       * @param value The make to set.
       * @return This builder for chaining.
       */
      public Builder setMake(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        make_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string make = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMake() {
        make_ = getDefaultInstance().getMake();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string make = 3;</code>
       * @param value The bytes for make to set.
       * @return This builder for chaining.
       */
      public Builder setMakeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        make_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object model_ = "";
      /**
       * <code>optional string model = 4;</code>
       * @return Whether the model field is set.
       */
      public boolean hasModel() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string model = 4;</code>
       * @return The model.
       */
      public java.lang.String getModel() {
        java.lang.Object ref = model_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            model_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string model = 4;</code>
       * @return The bytes for model.
       */
      public com.google.protobuf.ByteString
          getModelBytes() {
        java.lang.Object ref = model_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          model_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string model = 4;</code>
       * @param value The model to set.
       * @return This builder for chaining.
       */
      public Builder setModel(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        model_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional string model = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearModel() {
        model_ = getDefaultInstance().getModel();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>optional string model = 4;</code>
       * @param value The bytes for model to set.
       * @return This builder for chaining.
       */
      public Builder setModelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        model_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object year_ = "";
      /**
       * <code>optional string year = 5;</code>
       * @return Whether the year field is set.
       */
      public boolean hasYear() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string year = 5;</code>
       * @return The year.
       */
      public java.lang.String getYear() {
        java.lang.Object ref = year_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            year_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string year = 5;</code>
       * @return The bytes for year.
       */
      public com.google.protobuf.ByteString
          getYearBytes() {
        java.lang.Object ref = year_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          year_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string year = 5;</code>
       * @param value The year to set.
       * @return This builder for chaining.
       */
      public Builder setYear(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        year_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional string year = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearYear() {
        year_ = getDefaultInstance().getYear();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>optional string year = 5;</code>
       * @param value The bytes for year to set.
       * @return This builder for chaining.
       */
      public Builder setYearBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        year_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object headUnitSoftwareBuild_ = "";
      /**
       * <code>optional string head_unit_software_build = 6;</code>
       * @return Whether the headUnitSoftwareBuild field is set.
       */
      public boolean hasHeadUnitSoftwareBuild() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string head_unit_software_build = 6;</code>
       * @return The headUnitSoftwareBuild.
       */
      public java.lang.String getHeadUnitSoftwareBuild() {
        java.lang.Object ref = headUnitSoftwareBuild_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            headUnitSoftwareBuild_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string head_unit_software_build = 6;</code>
       * @return The bytes for headUnitSoftwareBuild.
       */
      public com.google.protobuf.ByteString
          getHeadUnitSoftwareBuildBytes() {
        java.lang.Object ref = headUnitSoftwareBuild_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headUnitSoftwareBuild_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string head_unit_software_build = 6;</code>
       * @param value The headUnitSoftwareBuild to set.
       * @return This builder for chaining.
       */
      public Builder setHeadUnitSoftwareBuild(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        headUnitSoftwareBuild_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional string head_unit_software_build = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeadUnitSoftwareBuild() {
        headUnitSoftwareBuild_ = getDefaultInstance().getHeadUnitSoftwareBuild();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>optional string head_unit_software_build = 6;</code>
       * @param value The bytes for headUnitSoftwareBuild to set.
       * @return This builder for chaining.
       */
      public Builder setHeadUnitSoftwareBuildBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        headUnitSoftwareBuild_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object vehicleId_ = "";
      /**
       * <code>optional string vehicle_id = 7;</code>
       * @return Whether the vehicleId field is set.
       */
      public boolean hasVehicleId() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional string vehicle_id = 7;</code>
       * @return The vehicleId.
       */
      public java.lang.String getVehicleId() {
        java.lang.Object ref = vehicleId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            vehicleId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string vehicle_id = 7;</code>
       * @return The bytes for vehicleId.
       */
      public com.google.protobuf.ByteString
          getVehicleIdBytes() {
        java.lang.Object ref = vehicleId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vehicleId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string vehicle_id = 7;</code>
       * @param value The vehicleId to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        vehicleId_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional string vehicle_id = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearVehicleId() {
        vehicleId_ = getDefaultInstance().getVehicleId();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>optional string vehicle_id = 7;</code>
       * @param value The bytes for vehicleId to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        vehicleId_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private java.lang.Object headUnitSoftwareVersion_ = "";
      /**
       * <code>optional string head_unit_software_version = 8;</code>
       * @return Whether the headUnitSoftwareVersion field is set.
       */
      public boolean hasHeadUnitSoftwareVersion() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional string head_unit_software_version = 8;</code>
       * @return The headUnitSoftwareVersion.
       */
      public java.lang.String getHeadUnitSoftwareVersion() {
        java.lang.Object ref = headUnitSoftwareVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            headUnitSoftwareVersion_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string head_unit_software_version = 8;</code>
       * @return The bytes for headUnitSoftwareVersion.
       */
      public com.google.protobuf.ByteString
          getHeadUnitSoftwareVersionBytes() {
        java.lang.Object ref = headUnitSoftwareVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headUnitSoftwareVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string head_unit_software_version = 8;</code>
       * @param value The headUnitSoftwareVersion to set.
       * @return This builder for chaining.
       */
      public Builder setHeadUnitSoftwareVersion(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        headUnitSoftwareVersion_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>optional string head_unit_software_version = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeadUnitSoftwareVersion() {
        headUnitSoftwareVersion_ = getDefaultInstance().getHeadUnitSoftwareVersion();
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>optional string head_unit_software_version = 8;</code>
       * @param value The bytes for headUnitSoftwareVersion to set.
       * @return This builder for chaining.
       */
      public Builder setHeadUnitSoftwareVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        headUnitSoftwareVersion_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dev.zanderp.opencfmoto.aa.proto.HeadUnitInfo)
    }

    // @@protoc_insertion_point(class_scope:dev.zanderp.opencfmoto.aa.proto.HeadUnitInfo)
    private static final dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo();
    }

    public static dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HeadUnitInfo>
        PARSER = new com.google.protobuf.AbstractParser<HeadUnitInfo>() {
      @java.lang.Override
      public HeadUnitInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<HeadUnitInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HeadUnitInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.zanderp.opencfmoto.aa.proto.Common.HeadUnitInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_HeadUnitInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_HeadUnitInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014common.proto\0221com.andrerinas.headunitr" +
      "evived.aap.protocol.proto\"\304\001\n\014HeadUnitIn" +
      "fo\022\026\n\016head_unit_make\030\001 \001(\t\022\027\n\017head_unit_" +
      "model\030\002 \001(\t\022\014\n\004make\030\003 \001(\t\022\r\n\005model\030\004 \001(\t" +
      "\022\014\n\004year\030\005 \001(\t\022 \n\030head_unit_software_bui" +
      "ld\030\006 \001(\t\022\022\n\nvehicle_id\030\007 \001(\t\022\"\n\032head_uni" +
      "t_software_version\030\010 \001(\t*\323\n\n\rMessageStat" +
      "us\022\022\n\016STATUS_SUCCESS\020\000\022\036\n\032STATUS_UNSOLIC" +
      "ITED_MESSAGE\020\001\022)\n\034STATUS_NO_COMPATIBLE_V" +
      "ERSION\020\377\377\377\377\377\377\377\377\377\001\022%\n\030STATUS_CERTIFICATE_" +
      "ERROR\020\376\377\377\377\377\377\377\377\377\001\022*\n\035STATUS_AUTHENTICATIO" +
      "N_FAILURE\020\375\377\377\377\377\377\377\377\377\001\022#\n\026STATUS_INVALID_S" +
      "ERVICE\020\374\377\377\377\377\377\377\377\377\001\022#\n\026STATUS_INVALID_CHAN" +
      "NEL\020\373\377\377\377\377\377\377\377\377\001\022$\n\027STATUS_INVALID_PRIORIT" +
      "Y\020\372\377\377\377\377\377\377\377\377\001\022\"\n\025STATUS_INTERNAL_ERROR\020\371\377" +
      "\377\377\377\377\377\377\377\001\022)\n\034STATUS_MEDIA_CONFIG_MISMATCH" +
      "\020\370\377\377\377\377\377\377\377\377\001\022\"\n\025STATUS_INVALID_SENSOR\020\367\377\377" +
      "\377\377\377\377\377\377\001\022-\n STATUS_BLUETOOTH_PAIRING_DELA" +
      "YED\020\366\377\377\377\377\377\377\377\377\001\022)\n\034STATUS_BLUETOOTH_UNAVA" +
      "ILABLE\020\365\377\377\377\377\377\377\377\377\001\022-\n STATUS_BLUETOOTH_IN" +
      "VALID_ADDRESS\020\364\377\377\377\377\377\377\377\377\001\0224\n\'STATUS_BLUET" +
      "OOTH_INVALID_PAIRING_METHOD\020\363\377\377\377\377\377\377\377\377\001\022/" +
      "\n\"STATUS_BLUETOOTH_INVALID_AUTH_DATA\020\362\377\377" +
      "\377\377\377\377\377\377\001\0220\n#STATUS_BLUETOOTH_AUTH_DATA_MI" +
      "SMATCH\020\361\377\377\377\377\377\377\377\377\001\0224\n\'STATUS_BLUETOOTH_HF" +
      "P_ANOTHER_CONNECTION\020\360\377\377\377\377\377\377\377\377\001\0224\n\'STATU" +
      "S_BLUETOOTH_HFP_CONNECTION_FAILURE\020\357\377\377\377\377" +
      "\377\377\377\377\001\022%\n\030STATUS_KEYCODE_NOT_BOUND\020\356\377\377\377\377\377" +
      "\377\377\377\001\022)\n\034STATUS_RADIO_INVALID_STATION\020\355\377\377" +
      "\377\377\377\377\377\377\001\022!\n\024STATUS_INVALID_INPUT\020\354\377\377\377\377\377\377\377" +
      "\377\001\0227\n*STATUS_RADIO_STATION_PRESETS_NOT_S" +
      "UPPORTED\020\353\377\377\377\377\377\377\377\377\001\022$\n\027STATUS_RADIO_COMM" +
      "_ERROR\020\352\377\377\377\377\377\377\377\377\001\022=\n0STATUS_AUTHENTICATI" +
      "ON_FAILURE_CERT_NOT_YET_VALID\020\351\377\377\377\377\377\377\377\377\001" +
      "\0227\n*STATUS_AUTHENTICATION_FAILURE_CERT_E" +
      "XPIRED\020\350\377\377\377\377\377\377\377\377\001\022 \n\023STATUS_PING_TIMEOUT" +
      "\020\347\377\377\377\377\377\377\377\377\001\022)\n\034STATUS_COMMAND_NOT_SUPPOR" +
      "TED\020\206\376\377\377\377\377\377\377\377\001\022!\n\024STATUS_FRAMING_ERROR\020\205" +
      "\376\377\377\377\377\377\377\377\001\022&\n\031STATUS_UNEXPECTED_MESSAGE\020\203" +
      "\376\377\377\377\377\377\377\377\001\022\030\n\013STATUS_BUSY\020\202\376\377\377\377\377\377\377\377\001\022!\n\024S" +
      "TATUS_OUT_OF_MEMORY\020\201\376\377\377\377\377\377\377\377\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_HeadUnitInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_HeadUnitInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_HeadUnitInfo_descriptor,
        new java.lang.String[] { "HeadUnitMake", "HeadUnitModel", "Make", "Model", "Year", "HeadUnitSoftwareBuild", "VehicleId", "HeadUnitSoftwareVersion", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
