// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: playback.proto

// Protobuf Java Version: 3.25.1
package dev.zanderp.opencfmoto.aa.proto;

public final class MediaPlayback {
  private MediaPlayback() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code dev.zanderp.opencfmoto.aa.proto.MsgType}
   */
  public enum MsgType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MSG_PLAYBACK_METADATA = 32769;</code>
     */
    MSG_PLAYBACK_METADATA(32769),
    /**
     * <code>MSG_PLAYBACK_STARTRESPONSE = 32770;</code>
     */
    MSG_PLAYBACK_STARTRESPONSE(32770),
    /**
     * <code>MSG_PLAYBACK_METADATASTART = 32771;</code>
     */
    MSG_PLAYBACK_METADATASTART(32771),
    ;

    /**
     * <code>MSG_PLAYBACK_METADATA = 32769;</code>
     */
    public static final int MSG_PLAYBACK_METADATA_VALUE = 32769;
    /**
     * <code>MSG_PLAYBACK_STARTRESPONSE = 32770;</code>
     */
    public static final int MSG_PLAYBACK_STARTRESPONSE_VALUE = 32770;
    /**
     * <code>MSG_PLAYBACK_METADATASTART = 32771;</code>
     */
    public static final int MSG_PLAYBACK_METADATASTART_VALUE = 32771;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MsgType forNumber(int value) {
      switch (value) {
        case 32769: return MSG_PLAYBACK_METADATA;
        case 32770: return MSG_PLAYBACK_STARTRESPONSE;
        case 32771: return MSG_PLAYBACK_METADATASTART;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgType>() {
            public MsgType findValueByNumber(int number) {
              return MsgType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return dev.zanderp.opencfmoto.aa.proto.MediaPlayback.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgType[] VALUES = values();

    public static MsgType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:dev.zanderp.opencfmoto.aa.proto.MsgType)
  }

  public interface MediaPlaybackStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dev.zanderp.opencfmoto.aa.proto.MediaPlaybackStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .dev.zanderp.opencfmoto.aa.proto.MediaPlaybackStatus.State state = 1;</code>
     * @return Whether the state field is set.
     */
    boolean hasState();
    /**
     * <code>optional .dev.zanderp.opencfmoto.aa.proto.MediaPlaybackStatus.State state = 1;</code>
     * @return The state.
     */
    dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.State getState();

    /**
     * <code>optional string media_source = 2;</code>
     * @return Whether the mediaSource field is set.
     */
    boolean hasMediaSource();
    /**
     * <code>optional string media_source = 2;</code>
     * @return The mediaSource.
     */
    java.lang.String getMediaSource();
    /**
     * <code>optional string media_source = 2;</code>
     * @return The bytes for mediaSource.
     */
    com.google.protobuf.ByteString
        getMediaSourceBytes();

    /**
     * <code>optional uint32 playback_seconds = 3;</code>
     * @return Whether the playbackSeconds field is set.
     */
    boolean hasPlaybackSeconds();
    /**
     * <code>optional uint32 playback_seconds = 3;</code>
     * @return The playbackSeconds.
     */
    int getPlaybackSeconds();

    /**
     * <code>optional bool shuffle = 4;</code>
     * @return Whether the shuffle field is set.
     */
    boolean hasShuffle();
    /**
     * <code>optional bool shuffle = 4;</code>
     * @return The shuffle.
     */
    boolean getShuffle();

    /**
     * <code>optional bool repeat = 5;</code>
     * @return Whether the repeat field is set.
     */
    boolean hasRepeat();
    /**
     * <code>optional bool repeat = 5;</code>
     * @return The repeat.
     */
    boolean getRepeat();

    /**
     * <code>optional bool repeat_one = 6;</code>
     * @return Whether the repeatOne field is set.
     */
    boolean hasRepeatOne();
    /**
     * <code>optional bool repeat_one = 6;</code>
     * @return The repeatOne.
     */
    boolean getRepeatOne();
  }
  /**
   * Protobuf type {@code dev.zanderp.opencfmoto.aa.proto.MediaPlaybackStatus}
   */
  public static final class MediaPlaybackStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dev.zanderp.opencfmoto.aa.proto.MediaPlaybackStatus)
      MediaPlaybackStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MediaPlaybackStatus.newBuilder() to construct.
    private MediaPlaybackStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MediaPlaybackStatus() {
      state_ = 1;
      mediaSource_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MediaPlaybackStatus();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.zanderp.opencfmoto.aa.proto.MediaPlayback.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaPlaybackStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.zanderp.opencfmoto.aa.proto.MediaPlayback.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaPlaybackStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.class, dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.Builder.class);
    }

    /**
     * Protobuf enum {@code dev.zanderp.opencfmoto.aa.proto.MediaPlaybackStatus.State}
     */
    public enum State
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>STOPPED = 1;</code>
       */
      STOPPED(1),
      /**
       * <code>PLAYING = 2;</code>
       */
      PLAYING(2),
      /**
       * <code>PAUSED = 3;</code>
       */
      PAUSED(3),
      ;

      /**
       * <code>STOPPED = 1;</code>
       */
      public static final int STOPPED_VALUE = 1;
      /**
       * <code>PLAYING = 2;</code>
       */
      public static final int PLAYING_VALUE = 2;
      /**
       * <code>PAUSED = 3;</code>
       */
      public static final int PAUSED_VALUE = 3;


      public final int getNumber() {
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static State valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static State forNumber(int value) {
        switch (value) {
          case 1: return STOPPED;
          case 2: return PLAYING;
          case 3: return PAUSED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<State>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          State> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<State>() {
              public State findValueByNumber(int number) {
                return State.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.getDescriptor().getEnumTypes().get(0);
      }

      private static final State[] VALUES = values();

      public static State valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private State(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:dev.zanderp.opencfmoto.aa.proto.MediaPlaybackStatus.State)
    }

    private int bitField0_;
    public static final int STATE_FIELD_NUMBER = 1;
    private int state_ = 1;
    /**
     * <code>optional .dev.zanderp.opencfmoto.aa.proto.MediaPlaybackStatus.State state = 1;</code>
     * @return Whether the state field is set.
     */
    @java.lang.Override public boolean hasState() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .dev.zanderp.opencfmoto.aa.proto.MediaPlaybackStatus.State state = 1;</code>
     * @return The state.
     */
    @java.lang.Override public dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.State getState() {
      dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.State result = dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.State.forNumber(state_);
      return result == null ? dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.State.STOPPED : result;
    }

    public static final int MEDIA_SOURCE_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object mediaSource_ = "";
    /**
     * <code>optional string media_source = 2;</code>
     * @return Whether the mediaSource field is set.
     */
    @java.lang.Override
    public boolean hasMediaSource() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string media_source = 2;</code>
     * @return The mediaSource.
     */
    @java.lang.Override
    public java.lang.String getMediaSource() {
      java.lang.Object ref = mediaSource_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mediaSource_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string media_source = 2;</code>
     * @return The bytes for mediaSource.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMediaSourceBytes() {
      java.lang.Object ref = mediaSource_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mediaSource_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYBACK_SECONDS_FIELD_NUMBER = 3;
    private int playbackSeconds_ = 0;
    /**
     * <code>optional uint32 playback_seconds = 3;</code>
     * @return Whether the playbackSeconds field is set.
     */
    @java.lang.Override
    public boolean hasPlaybackSeconds() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint32 playback_seconds = 3;</code>
     * @return The playbackSeconds.
     */
    @java.lang.Override
    public int getPlaybackSeconds() {
      return playbackSeconds_;
    }

    public static final int SHUFFLE_FIELD_NUMBER = 4;
    private boolean shuffle_ = false;
    /**
     * <code>optional bool shuffle = 4;</code>
     * @return Whether the shuffle field is set.
     */
    @java.lang.Override
    public boolean hasShuffle() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bool shuffle = 4;</code>
     * @return The shuffle.
     */
    @java.lang.Override
    public boolean getShuffle() {
      return shuffle_;
    }

    public static final int REPEAT_FIELD_NUMBER = 5;
    private boolean repeat_ = false;
    /**
     * <code>optional bool repeat = 5;</code>
     * @return Whether the repeat field is set.
     */
    @java.lang.Override
    public boolean hasRepeat() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional bool repeat = 5;</code>
     * @return The repeat.
     */
    @java.lang.Override
    public boolean getRepeat() {
      return repeat_;
    }

    public static final int REPEAT_ONE_FIELD_NUMBER = 6;
    private boolean repeatOne_ = false;
    /**
     * <code>optional bool repeat_one = 6;</code>
     * @return Whether the repeatOne field is set.
     */
    @java.lang.Override
    public boolean hasRepeatOne() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional bool repeat_one = 6;</code>
     * @return The repeatOne.
     */
    @java.lang.Override
    public boolean getRepeatOne() {
      return repeatOne_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, state_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mediaSource_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt32(3, playbackSeconds_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBool(4, shuffle_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBool(5, repeat_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeBool(6, repeatOne_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, state_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mediaSource_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, playbackSeconds_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, shuffle_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, repeat_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, repeatOne_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus)) {
        return super.equals(obj);
      }
      dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus other = (dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus) obj;

      if (hasState() != other.hasState()) return false;
      if (hasState()) {
        if (state_ != other.state_) return false;
      }
      if (hasMediaSource() != other.hasMediaSource()) return false;
      if (hasMediaSource()) {
        if (!getMediaSource()
            .equals(other.getMediaSource())) return false;
      }
      if (hasPlaybackSeconds() != other.hasPlaybackSeconds()) return false;
      if (hasPlaybackSeconds()) {
        if (getPlaybackSeconds()
            != other.getPlaybackSeconds()) return false;
      }
      if (hasShuffle() != other.hasShuffle()) return false;
      if (hasShuffle()) {
        if (getShuffle()
            != other.getShuffle()) return false;
      }
      if (hasRepeat() != other.hasRepeat()) return false;
      if (hasRepeat()) {
        if (getRepeat()
            != other.getRepeat()) return false;
      }
      if (hasRepeatOne() != other.hasRepeatOne()) return false;
      if (hasRepeatOne()) {
        if (getRepeatOne()
            != other.getRepeatOne()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + state_;
      }
      if (hasMediaSource()) {
        hash = (37 * hash) + MEDIA_SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getMediaSource().hashCode();
      }
      if (hasPlaybackSeconds()) {
        hash = (37 * hash) + PLAYBACK_SECONDS_FIELD_NUMBER;
        hash = (53 * hash) + getPlaybackSeconds();
      }
      if (hasShuffle()) {
        hash = (37 * hash) + SHUFFLE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getShuffle());
      }
      if (hasRepeat()) {
        hash = (37 * hash) + REPEAT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getRepeat());
      }
      if (hasRepeatOne()) {
        hash = (37 * hash) + REPEAT_ONE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getRepeatOne());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dev.zanderp.opencfmoto.aa.proto.MediaPlaybackStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dev.zanderp.opencfmoto.aa.proto.MediaPlaybackStatus)
        dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.zanderp.opencfmoto.aa.proto.MediaPlayback.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaPlaybackStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.zanderp.opencfmoto.aa.proto.MediaPlayback.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaPlaybackStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.class, dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.Builder.class);
      }

      // Construct using dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        state_ = 1;
        mediaSource_ = "";
        playbackSeconds_ = 0;
        shuffle_ = false;
        repeat_ = false;
        repeatOne_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.zanderp.opencfmoto.aa.proto.MediaPlayback.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaPlaybackStatus_descriptor;
      }

      @java.lang.Override
      public dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus getDefaultInstanceForType() {
        return dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.getDefaultInstance();
      }

      @java.lang.Override
      public dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus build() {
        dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus buildPartial() {
        dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus result = new dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.state_ = state_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.mediaSource_ = mediaSource_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.playbackSeconds_ = playbackSeconds_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.shuffle_ = shuffle_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.repeat_ = repeat_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.repeatOne_ = repeatOne_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus) {
          return mergeFrom((dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus other) {
        if (other == dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.getDefaultInstance()) return this;
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasMediaSource()) {
          mediaSource_ = other.mediaSource_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasPlaybackSeconds()) {
          setPlaybackSeconds(other.getPlaybackSeconds());
        }
        if (other.hasShuffle()) {
          setShuffle(other.getShuffle());
        }
        if (other.hasRepeat()) {
          setRepeat(other.getRepeat());
        }
        if (other.hasRepeatOne()) {
          setRepeatOne(other.getRepeatOne());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int tmpRaw = input.readEnum();
                dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.State tmpValue =
                    dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.State.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(1, tmpRaw);
                } else {
                  state_ = tmpRaw;
                  bitField0_ |= 0x00000001;
                }
                break;
              } // case 8
              case 18: {
                mediaSource_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                playbackSeconds_ = input.readUInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                shuffle_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                repeat_ = input.readBool();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                repeatOne_ = input.readBool();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int state_ = 1;
      /**
       * <code>optional .dev.zanderp.opencfmoto.aa.proto.MediaPlaybackStatus.State state = 1;</code>
       * @return Whether the state field is set.
       */
      @java.lang.Override public boolean hasState() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .dev.zanderp.opencfmoto.aa.proto.MediaPlaybackStatus.State state = 1;</code>
       * @return The state.
       */
      @java.lang.Override
      public dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.State getState() {
        dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.State result = dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.State.forNumber(state_);
        return result == null ? dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.State.STOPPED : result;
      }
      /**
       * <code>optional .dev.zanderp.opencfmoto.aa.proto.MediaPlaybackStatus.State state = 1;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus.State value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .dev.zanderp.opencfmoto.aa.proto.MediaPlaybackStatus.State state = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object mediaSource_ = "";
      /**
       * <code>optional string media_source = 2;</code>
       * @return Whether the mediaSource field is set.
       */
      public boolean hasMediaSource() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string media_source = 2;</code>
       * @return The mediaSource.
       */
      public java.lang.String getMediaSource() {
        java.lang.Object ref = mediaSource_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mediaSource_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string media_source = 2;</code>
       * @return The bytes for mediaSource.
       */
      public com.google.protobuf.ByteString
          getMediaSourceBytes() {
        java.lang.Object ref = mediaSource_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mediaSource_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string media_source = 2;</code>
       * @param value The mediaSource to set.
       * @return This builder for chaining.
       */
      public Builder setMediaSource(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        mediaSource_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string media_source = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMediaSource() {
        mediaSource_ = getDefaultInstance().getMediaSource();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string media_source = 2;</code>
       * @param value The bytes for mediaSource to set.
       * @return This builder for chaining.
       */
      public Builder setMediaSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        mediaSource_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int playbackSeconds_ ;
      /**
       * <code>optional uint32 playback_seconds = 3;</code>
       * @return Whether the playbackSeconds field is set.
       */
      @java.lang.Override
      public boolean hasPlaybackSeconds() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional uint32 playback_seconds = 3;</code>
       * @return The playbackSeconds.
       */
      @java.lang.Override
      public int getPlaybackSeconds() {
        return playbackSeconds_;
      }
      /**
       * <code>optional uint32 playback_seconds = 3;</code>
       * @param value The playbackSeconds to set.
       * @return This builder for chaining.
       */
      public Builder setPlaybackSeconds(int value) {

        playbackSeconds_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 playback_seconds = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlaybackSeconds() {
        bitField0_ = (bitField0_ & ~0x00000004);
        playbackSeconds_ = 0;
        onChanged();
        return this;
      }

      private boolean shuffle_ ;
      /**
       * <code>optional bool shuffle = 4;</code>
       * @return Whether the shuffle field is set.
       */
      @java.lang.Override
      public boolean hasShuffle() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bool shuffle = 4;</code>
       * @return The shuffle.
       */
      @java.lang.Override
      public boolean getShuffle() {
        return shuffle_;
      }
      /**
       * <code>optional bool shuffle = 4;</code>
       * @param value The shuffle to set.
       * @return This builder for chaining.
       */
      public Builder setShuffle(boolean value) {

        shuffle_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool shuffle = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearShuffle() {
        bitField0_ = (bitField0_ & ~0x00000008);
        shuffle_ = false;
        onChanged();
        return this;
      }

      private boolean repeat_ ;
      /**
       * <code>optional bool repeat = 5;</code>
       * @return Whether the repeat field is set.
       */
      @java.lang.Override
      public boolean hasRepeat() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional bool repeat = 5;</code>
       * @return The repeat.
       */
      @java.lang.Override
      public boolean getRepeat() {
        return repeat_;
      }
      /**
       * <code>optional bool repeat = 5;</code>
       * @param value The repeat to set.
       * @return This builder for chaining.
       */
      public Builder setRepeat(boolean value) {

        repeat_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool repeat = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearRepeat() {
        bitField0_ = (bitField0_ & ~0x00000010);
        repeat_ = false;
        onChanged();
        return this;
      }

      private boolean repeatOne_ ;
      /**
       * <code>optional bool repeat_one = 6;</code>
       * @return Whether the repeatOne field is set.
       */
      @java.lang.Override
      public boolean hasRepeatOne() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional bool repeat_one = 6;</code>
       * @return The repeatOne.
       */
      @java.lang.Override
      public boolean getRepeatOne() {
        return repeatOne_;
      }
      /**
       * <code>optional bool repeat_one = 6;</code>
       * @param value The repeatOne to set.
       * @return This builder for chaining.
       */
      public Builder setRepeatOne(boolean value) {

        repeatOne_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool repeat_one = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearRepeatOne() {
        bitField0_ = (bitField0_ & ~0x00000020);
        repeatOne_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dev.zanderp.opencfmoto.aa.proto.MediaPlaybackStatus)
    }

    // @@protoc_insertion_point(class_scope:dev.zanderp.opencfmoto.aa.proto.MediaPlaybackStatus)
    private static final dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus();
    }

    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MediaPlaybackStatus>
        PARSER = new com.google.protobuf.AbstractParser<MediaPlaybackStatus>() {
      @java.lang.Override
      public MediaPlaybackStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MediaPlaybackStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MediaPlaybackStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaPlaybackStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MediaMetaDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dev.zanderp.opencfmoto.aa.proto.MediaMetaData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string song = 1;</code>
     * @return Whether the song field is set.
     */
    boolean hasSong();
    /**
     * <code>optional string song = 1;</code>
     * @return The song.
     */
    java.lang.String getSong();
    /**
     * <code>optional string song = 1;</code>
     * @return The bytes for song.
     */
    com.google.protobuf.ByteString
        getSongBytes();

    /**
     * <code>optional string artist = 2;</code>
     * @return Whether the artist field is set.
     */
    boolean hasArtist();
    /**
     * <code>optional string artist = 2;</code>
     * @return The artist.
     */
    java.lang.String getArtist();
    /**
     * <code>optional string artist = 2;</code>
     * @return The bytes for artist.
     */
    com.google.protobuf.ByteString
        getArtistBytes();

    /**
     * <code>optional string album = 3;</code>
     * @return Whether the album field is set.
     */
    boolean hasAlbum();
    /**
     * <code>optional string album = 3;</code>
     * @return The album.
     */
    java.lang.String getAlbum();
    /**
     * <code>optional string album = 3;</code>
     * @return The bytes for album.
     */
    com.google.protobuf.ByteString
        getAlbumBytes();

    /**
     * <code>optional bytes album_art = 4;</code>
     * @return Whether the albumArt field is set.
     */
    boolean hasAlbumArt();
    /**
     * <code>optional bytes album_art = 4;</code>
     * @return The albumArt.
     */
    com.google.protobuf.ByteString getAlbumArt();

    /**
     * <code>optional string playlist = 5;</code>
     * @return Whether the playlist field is set.
     */
    boolean hasPlaylist();
    /**
     * <code>optional string playlist = 5;</code>
     * @return The playlist.
     */
    java.lang.String getPlaylist();
    /**
     * <code>optional string playlist = 5;</code>
     * @return The bytes for playlist.
     */
    com.google.protobuf.ByteString
        getPlaylistBytes();

    /**
     * <code>optional uint32 duration_seconds = 6;</code>
     * @return Whether the durationSeconds field is set.
     */
    boolean hasDurationSeconds();
    /**
     * <code>optional uint32 duration_seconds = 6;</code>
     * @return The durationSeconds.
     */
    int getDurationSeconds();

    /**
     * <code>optional int32 rating = 7;</code>
     * @return Whether the rating field is set.
     */
    boolean hasRating();
    /**
     * <code>optional int32 rating = 7;</code>
     * @return The rating.
     */
    int getRating();
  }
  /**
   * Protobuf type {@code dev.zanderp.opencfmoto.aa.proto.MediaMetaData}
   */
  public static final class MediaMetaData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dev.zanderp.opencfmoto.aa.proto.MediaMetaData)
      MediaMetaDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MediaMetaData.newBuilder() to construct.
    private MediaMetaData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MediaMetaData() {
      song_ = "";
      artist_ = "";
      album_ = "";
      albumArt_ = com.google.protobuf.ByteString.EMPTY;
      playlist_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MediaMetaData();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.zanderp.opencfmoto.aa.proto.MediaPlayback.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaMetaData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.zanderp.opencfmoto.aa.proto.MediaPlayback.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaMetaData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData.class, dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData.Builder.class);
    }

    private int bitField0_;
    public static final int SONG_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object song_ = "";
    /**
     * <code>optional string song = 1;</code>
     * @return Whether the song field is set.
     */
    @java.lang.Override
    public boolean hasSong() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string song = 1;</code>
     * @return The song.
     */
    @java.lang.Override
    public java.lang.String getSong() {
      java.lang.Object ref = song_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          song_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string song = 1;</code>
     * @return The bytes for song.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSongBytes() {
      java.lang.Object ref = song_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        song_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARTIST_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object artist_ = "";
    /**
     * <code>optional string artist = 2;</code>
     * @return Whether the artist field is set.
     */
    @java.lang.Override
    public boolean hasArtist() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string artist = 2;</code>
     * @return The artist.
     */
    @java.lang.Override
    public java.lang.String getArtist() {
      java.lang.Object ref = artist_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          artist_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string artist = 2;</code>
     * @return The bytes for artist.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getArtistBytes() {
      java.lang.Object ref = artist_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        artist_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALBUM_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object album_ = "";
    /**
     * <code>optional string album = 3;</code>
     * @return Whether the album field is set.
     */
    @java.lang.Override
    public boolean hasAlbum() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string album = 3;</code>
     * @return The album.
     */
    @java.lang.Override
    public java.lang.String getAlbum() {
      java.lang.Object ref = album_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          album_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string album = 3;</code>
     * @return The bytes for album.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAlbumBytes() {
      java.lang.Object ref = album_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        album_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALBUM_ART_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString albumArt_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes album_art = 4;</code>
     * @return Whether the albumArt field is set.
     */
    @java.lang.Override
    public boolean hasAlbumArt() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional bytes album_art = 4;</code>
     * @return The albumArt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getAlbumArt() {
      return albumArt_;
    }

    public static final int PLAYLIST_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object playlist_ = "";
    /**
     * <code>optional string playlist = 5;</code>
     * @return Whether the playlist field is set.
     */
    @java.lang.Override
    public boolean hasPlaylist() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string playlist = 5;</code>
     * @return The playlist.
     */
    @java.lang.Override
    public java.lang.String getPlaylist() {
      java.lang.Object ref = playlist_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          playlist_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string playlist = 5;</code>
     * @return The bytes for playlist.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlaylistBytes() {
      java.lang.Object ref = playlist_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        playlist_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DURATION_SECONDS_FIELD_NUMBER = 6;
    private int durationSeconds_ = 0;
    /**
     * <code>optional uint32 duration_seconds = 6;</code>
     * @return Whether the durationSeconds field is set.
     */
    @java.lang.Override
    public boolean hasDurationSeconds() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional uint32 duration_seconds = 6;</code>
     * @return The durationSeconds.
     */
    @java.lang.Override
    public int getDurationSeconds() {
      return durationSeconds_;
    }

    public static final int RATING_FIELD_NUMBER = 7;
    private int rating_ = 0;
    /**
     * <code>optional int32 rating = 7;</code>
     * @return Whether the rating field is set.
     */
    @java.lang.Override
    public boolean hasRating() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional int32 rating = 7;</code>
     * @return The rating.
     */
    @java.lang.Override
    public int getRating() {
      return rating_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, song_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, artist_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, album_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBytes(4, albumArt_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, playlist_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeUInt32(6, durationSeconds_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt32(7, rating_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, song_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, artist_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, album_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, albumArt_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, playlist_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, durationSeconds_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, rating_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData)) {
        return super.equals(obj);
      }
      dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData other = (dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData) obj;

      if (hasSong() != other.hasSong()) return false;
      if (hasSong()) {
        if (!getSong()
            .equals(other.getSong())) return false;
      }
      if (hasArtist() != other.hasArtist()) return false;
      if (hasArtist()) {
        if (!getArtist()
            .equals(other.getArtist())) return false;
      }
      if (hasAlbum() != other.hasAlbum()) return false;
      if (hasAlbum()) {
        if (!getAlbum()
            .equals(other.getAlbum())) return false;
      }
      if (hasAlbumArt() != other.hasAlbumArt()) return false;
      if (hasAlbumArt()) {
        if (!getAlbumArt()
            .equals(other.getAlbumArt())) return false;
      }
      if (hasPlaylist() != other.hasPlaylist()) return false;
      if (hasPlaylist()) {
        if (!getPlaylist()
            .equals(other.getPlaylist())) return false;
      }
      if (hasDurationSeconds() != other.hasDurationSeconds()) return false;
      if (hasDurationSeconds()) {
        if (getDurationSeconds()
            != other.getDurationSeconds()) return false;
      }
      if (hasRating() != other.hasRating()) return false;
      if (hasRating()) {
        if (getRating()
            != other.getRating()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSong()) {
        hash = (37 * hash) + SONG_FIELD_NUMBER;
        hash = (53 * hash) + getSong().hashCode();
      }
      if (hasArtist()) {
        hash = (37 * hash) + ARTIST_FIELD_NUMBER;
        hash = (53 * hash) + getArtist().hashCode();
      }
      if (hasAlbum()) {
        hash = (37 * hash) + ALBUM_FIELD_NUMBER;
        hash = (53 * hash) + getAlbum().hashCode();
      }
      if (hasAlbumArt()) {
        hash = (37 * hash) + ALBUM_ART_FIELD_NUMBER;
        hash = (53 * hash) + getAlbumArt().hashCode();
      }
      if (hasPlaylist()) {
        hash = (37 * hash) + PLAYLIST_FIELD_NUMBER;
        hash = (53 * hash) + getPlaylist().hashCode();
      }
      if (hasDurationSeconds()) {
        hash = (37 * hash) + DURATION_SECONDS_FIELD_NUMBER;
        hash = (53 * hash) + getDurationSeconds();
      }
      if (hasRating()) {
        hash = (37 * hash) + RATING_FIELD_NUMBER;
        hash = (53 * hash) + getRating();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dev.zanderp.opencfmoto.aa.proto.MediaMetaData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dev.zanderp.opencfmoto.aa.proto.MediaMetaData)
        dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.zanderp.opencfmoto.aa.proto.MediaPlayback.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaMetaData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.zanderp.opencfmoto.aa.proto.MediaPlayback.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaMetaData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData.class, dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData.Builder.class);
      }

      // Construct using dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        song_ = "";
        artist_ = "";
        album_ = "";
        albumArt_ = com.google.protobuf.ByteString.EMPTY;
        playlist_ = "";
        durationSeconds_ = 0;
        rating_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.zanderp.opencfmoto.aa.proto.MediaPlayback.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaMetaData_descriptor;
      }

      @java.lang.Override
      public dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData getDefaultInstanceForType() {
        return dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData.getDefaultInstance();
      }

      @java.lang.Override
      public dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData build() {
        dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData buildPartial() {
        dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData result = new dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.song_ = song_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.artist_ = artist_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.album_ = album_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.albumArt_ = albumArt_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.playlist_ = playlist_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.durationSeconds_ = durationSeconds_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.rating_ = rating_;
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData) {
          return mergeFrom((dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData other) {
        if (other == dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData.getDefaultInstance()) return this;
        if (other.hasSong()) {
          song_ = other.song_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasArtist()) {
          artist_ = other.artist_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasAlbum()) {
          album_ = other.album_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasAlbumArt()) {
          setAlbumArt(other.getAlbumArt());
        }
        if (other.hasPlaylist()) {
          playlist_ = other.playlist_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.hasDurationSeconds()) {
          setDurationSeconds(other.getDurationSeconds());
        }
        if (other.hasRating()) {
          setRating(other.getRating());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                song_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                artist_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                album_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                albumArt_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                playlist_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 48: {
                durationSeconds_ = input.readUInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                rating_ = input.readInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object song_ = "";
      /**
       * <code>optional string song = 1;</code>
       * @return Whether the song field is set.
       */
      public boolean hasSong() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string song = 1;</code>
       * @return The song.
       */
      public java.lang.String getSong() {
        java.lang.Object ref = song_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            song_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string song = 1;</code>
       * @return The bytes for song.
       */
      public com.google.protobuf.ByteString
          getSongBytes() {
        java.lang.Object ref = song_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          song_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string song = 1;</code>
       * @param value The song to set.
       * @return This builder for chaining.
       */
      public Builder setSong(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        song_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string song = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSong() {
        song_ = getDefaultInstance().getSong();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string song = 1;</code>
       * @param value The bytes for song to set.
       * @return This builder for chaining.
       */
      public Builder setSongBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        song_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object artist_ = "";
      /**
       * <code>optional string artist = 2;</code>
       * @return Whether the artist field is set.
       */
      public boolean hasArtist() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string artist = 2;</code>
       * @return The artist.
       */
      public java.lang.String getArtist() {
        java.lang.Object ref = artist_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            artist_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string artist = 2;</code>
       * @return The bytes for artist.
       */
      public com.google.protobuf.ByteString
          getArtistBytes() {
        java.lang.Object ref = artist_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          artist_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string artist = 2;</code>
       * @param value The artist to set.
       * @return This builder for chaining.
       */
      public Builder setArtist(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        artist_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>optional string artist = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearArtist() {
        artist_ = getDefaultInstance().getArtist();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>optional string artist = 2;</code>
       * @param value The bytes for artist to set.
       * @return This builder for chaining.
       */
      public Builder setArtistBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        artist_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object album_ = "";
      /**
       * <code>optional string album = 3;</code>
       * @return Whether the album field is set.
       */
      public boolean hasAlbum() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string album = 3;</code>
       * @return The album.
       */
      public java.lang.String getAlbum() {
        java.lang.Object ref = album_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            album_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string album = 3;</code>
       * @return The bytes for album.
       */
      public com.google.protobuf.ByteString
          getAlbumBytes() {
        java.lang.Object ref = album_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          album_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string album = 3;</code>
       * @param value The album to set.
       * @return This builder for chaining.
       */
      public Builder setAlbum(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        album_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string album = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlbum() {
        album_ = getDefaultInstance().getAlbum();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string album = 3;</code>
       * @param value The bytes for album to set.
       * @return This builder for chaining.
       */
      public Builder setAlbumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        album_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString albumArt_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes album_art = 4;</code>
       * @return Whether the albumArt field is set.
       */
      @java.lang.Override
      public boolean hasAlbumArt() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional bytes album_art = 4;</code>
       * @return The albumArt.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getAlbumArt() {
        return albumArt_;
      }
      /**
       * <code>optional bytes album_art = 4;</code>
       * @param value The albumArt to set.
       * @return This builder for chaining.
       */
      public Builder setAlbumArt(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        albumArt_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes album_art = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlbumArt() {
        bitField0_ = (bitField0_ & ~0x00000008);
        albumArt_ = getDefaultInstance().getAlbumArt();
        onChanged();
        return this;
      }

      private java.lang.Object playlist_ = "";
      /**
       * <code>optional string playlist = 5;</code>
       * @return Whether the playlist field is set.
       */
      public boolean hasPlaylist() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string playlist = 5;</code>
       * @return The playlist.
       */
      public java.lang.String getPlaylist() {
        java.lang.Object ref = playlist_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            playlist_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string playlist = 5;</code>
       * @return The bytes for playlist.
       */
      public com.google.protobuf.ByteString
          getPlaylistBytes() {
        java.lang.Object ref = playlist_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          playlist_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string playlist = 5;</code>
       * @param value The playlist to set.
       * @return This builder for chaining.
       */
      public Builder setPlaylist(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        playlist_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional string playlist = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlaylist() {
        playlist_ = getDefaultInstance().getPlaylist();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>optional string playlist = 5;</code>
       * @param value The bytes for playlist to set.
       * @return This builder for chaining.
       */
      public Builder setPlaylistBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        playlist_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private int durationSeconds_ ;
      /**
       * <code>optional uint32 duration_seconds = 6;</code>
       * @return Whether the durationSeconds field is set.
       */
      @java.lang.Override
      public boolean hasDurationSeconds() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional uint32 duration_seconds = 6;</code>
       * @return The durationSeconds.
       */
      @java.lang.Override
      public int getDurationSeconds() {
        return durationSeconds_;
      }
      /**
       * <code>optional uint32 duration_seconds = 6;</code>
       * @param value The durationSeconds to set.
       * @return This builder for chaining.
       */
      public Builder setDurationSeconds(int value) {

        durationSeconds_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 duration_seconds = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDurationSeconds() {
        bitField0_ = (bitField0_ & ~0x00000020);
        durationSeconds_ = 0;
        onChanged();
        return this;
      }

      private int rating_ ;
      /**
       * <code>optional int32 rating = 7;</code>
       * @return Whether the rating field is set.
       */
      @java.lang.Override
      public boolean hasRating() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional int32 rating = 7;</code>
       * @return The rating.
       */
      @java.lang.Override
      public int getRating() {
        return rating_;
      }
      /**
       * <code>optional int32 rating = 7;</code>
       * @param value The rating to set.
       * @return This builder for chaining.
       */
      public Builder setRating(int value) {

        rating_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 rating = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearRating() {
        bitField0_ = (bitField0_ & ~0x00000040);
        rating_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dev.zanderp.opencfmoto.aa.proto.MediaMetaData)
    }

    // @@protoc_insertion_point(class_scope:dev.zanderp.opencfmoto.aa.proto.MediaMetaData)
    private static final dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData();
    }

    public static dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MediaMetaData>
        PARSER = new com.google.protobuf.AbstractParser<MediaMetaData>() {
      @java.lang.Override
      public MediaMetaData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MediaMetaData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MediaMetaData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.zanderp.opencfmoto.aa.proto.MediaPlayback.MediaMetaData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaPlaybackStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaPlaybackStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaMetaData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaMetaData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016playback.proto\0221com.andrerinas.headuni" +
      "trevived.aap.protocol.proto\"\206\002\n\023MediaPla" +
      "ybackStatus\022[\n\005state\030\001 \001(\0162L.com.andreri" +
      "nas.headunitrevived.aap.protocol.proto.M" +
      "ediaPlaybackStatus.State\022\024\n\014media_source" +
      "\030\002 \001(\t\022\030\n\020playback_seconds\030\003 \001(\r\022\017\n\007shuf" +
      "fle\030\004 \001(\010\022\016\n\006repeat\030\005 \001(\010\022\022\n\nrepeat_one\030" +
      "\006 \001(\010\"-\n\005State\022\013\n\007STOPPED\020\001\022\013\n\007PLAYING\020\002" +
      "\022\n\n\006PAUSED\020\003\"\213\001\n\rMediaMetaData\022\014\n\004song\030\001" +
      " \001(\t\022\016\n\006artist\030\002 \001(\t\022\r\n\005album\030\003 \001(\t\022\021\n\ta" +
      "lbum_art\030\004 \001(\014\022\020\n\010playlist\030\005 \001(\t\022\030\n\020dura" +
      "tion_seconds\030\006 \001(\r\022\016\n\006rating\030\007 \001(\005*j\n\007Ms" +
      "gType\022\033\n\025MSG_PLAYBACK_METADATA\020\201\200\002\022 \n\032MS" +
      "G_PLAYBACK_STARTRESPONSE\020\202\200\002\022 \n\032MSG_PLAY" +
      "BACK_METADATASTART\020\203\200\002B\017B\rMediaPlayback"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaPlaybackStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaPlaybackStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaPlaybackStatus_descriptor,
        new java.lang.String[] { "State", "MediaSource", "PlaybackSeconds", "Shuffle", "Repeat", "RepeatOne", });
    internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaMetaData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaMetaData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_MediaMetaData_descriptor,
        new java.lang.String[] { "Song", "Artist", "Album", "AlbumArt", "Playlist", "DurationSeconds", "Rating", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
