// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wireless.proto

// Protobuf Java Version: 3.25.1
package dev.zanderp.opencfmoto.aa.proto;

public final class Wireless {
  private Wireless() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code dev.zanderp.opencfmoto.aa.proto.AccessPointType}
   */
  public enum AccessPointType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STATIC = 0;</code>
     */
    STATIC(0),
    /**
     * <code>DYNAMIC = 1;</code>
     */
    DYNAMIC(1),
    ;

    /**
     * <code>STATIC = 0;</code>
     */
    public static final int STATIC_VALUE = 0;
    /**
     * <code>DYNAMIC = 1;</code>
     */
    public static final int DYNAMIC_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AccessPointType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AccessPointType forNumber(int value) {
      switch (value) {
        case 0: return STATIC;
        case 1: return DYNAMIC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AccessPointType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AccessPointType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AccessPointType>() {
            public AccessPointType findValueByNumber(int number) {
              return AccessPointType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return dev.zanderp.opencfmoto.aa.proto.Wireless.getDescriptor().getEnumTypes().get(0);
    }

    private static final AccessPointType[] VALUES = values();

    public static AccessPointType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AccessPointType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:dev.zanderp.opencfmoto.aa.proto.AccessPointType)
  }

  /**
   * Protobuf enum {@code dev.zanderp.opencfmoto.aa.proto.SecurityMode}
   */
  public enum SecurityMode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_SECURITY_MODE = 0;</code>
     */
    UNKNOWN_SECURITY_MODE(0),
    /**
     * <code>OPEN = 1;</code>
     */
    OPEN(1),
    /**
     * <code>WEP_64 = 2;</code>
     */
    WEP_64(2),
    /**
     * <code>WEP_128 = 3;</code>
     */
    WEP_128(3),
    /**
     * <code>WPA_PERSONAL = 4;</code>
     */
    WPA_PERSONAL(4),
    /**
     * <code>WPA2_PERSONAL = 8;</code>
     */
    WPA2_PERSONAL(8),
    /**
     * <code>WPA_WPA2_PERSONAL = 12;</code>
     */
    WPA_WPA2_PERSONAL(12),
    /**
     * <code>WPA_ENTERPRISE = 20;</code>
     */
    WPA_ENTERPRISE(20),
    /**
     * <code>WPA2_ENTERPRISE = 24;</code>
     */
    WPA2_ENTERPRISE(24),
    /**
     * <code>WPA_WPA2_ENTERPRISE = 28;</code>
     */
    WPA_WPA2_ENTERPRISE(28),
    ;

    /**
     * <code>UNKNOWN_SECURITY_MODE = 0;</code>
     */
    public static final int UNKNOWN_SECURITY_MODE_VALUE = 0;
    /**
     * <code>OPEN = 1;</code>
     */
    public static final int OPEN_VALUE = 1;
    /**
     * <code>WEP_64 = 2;</code>
     */
    public static final int WEP_64_VALUE = 2;
    /**
     * <code>WEP_128 = 3;</code>
     */
    public static final int WEP_128_VALUE = 3;
    /**
     * <code>WPA_PERSONAL = 4;</code>
     */
    public static final int WPA_PERSONAL_VALUE = 4;
    /**
     * <code>WPA2_PERSONAL = 8;</code>
     */
    public static final int WPA2_PERSONAL_VALUE = 8;
    /**
     * <code>WPA_WPA2_PERSONAL = 12;</code>
     */
    public static final int WPA_WPA2_PERSONAL_VALUE = 12;
    /**
     * <code>WPA_ENTERPRISE = 20;</code>
     */
    public static final int WPA_ENTERPRISE_VALUE = 20;
    /**
     * <code>WPA2_ENTERPRISE = 24;</code>
     */
    public static final int WPA2_ENTERPRISE_VALUE = 24;
    /**
     * <code>WPA_WPA2_ENTERPRISE = 28;</code>
     */
    public static final int WPA_WPA2_ENTERPRISE_VALUE = 28;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SecurityMode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SecurityMode forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_SECURITY_MODE;
        case 1: return OPEN;
        case 2: return WEP_64;
        case 3: return WEP_128;
        case 4: return WPA_PERSONAL;
        case 8: return WPA2_PERSONAL;
        case 12: return WPA_WPA2_PERSONAL;
        case 20: return WPA_ENTERPRISE;
        case 24: return WPA2_ENTERPRISE;
        case 28: return WPA_WPA2_ENTERPRISE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SecurityMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SecurityMode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SecurityMode>() {
            public SecurityMode findValueByNumber(int number) {
              return SecurityMode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return dev.zanderp.opencfmoto.aa.proto.Wireless.getDescriptor().getEnumTypes().get(1);
    }

    private static final SecurityMode[] VALUES = values();

    public static SecurityMode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SecurityMode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:dev.zanderp.opencfmoto.aa.proto.SecurityMode)
  }

  public interface WifiStartRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dev.zanderp.opencfmoto.aa.proto.WifiStartRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string ip_address = 1;</code>
     * @return Whether the ipAddress field is set.
     */
    boolean hasIpAddress();
    /**
     * <code>required string ip_address = 1;</code>
     * @return The ipAddress.
     */
    java.lang.String getIpAddress();
    /**
     * <code>required string ip_address = 1;</code>
     * @return The bytes for ipAddress.
     */
    com.google.protobuf.ByteString
        getIpAddressBytes();

    /**
     * <code>required int32 port = 2;</code>
     * @return Whether the port field is set.
     */
    boolean hasPort();
    /**
     * <code>required int32 port = 2;</code>
     * @return The port.
     */
    int getPort();

    /**
     * <code>optional int32 status = 3;</code>
     * @return Whether the status field is set.
     */
    boolean hasStatus();
    /**
     * <code>optional int32 status = 3;</code>
     * @return The status.
     */
    int getStatus();
  }
  /**
   * Protobuf type {@code dev.zanderp.opencfmoto.aa.proto.WifiStartRequest}
   */
  public static final class WifiStartRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dev.zanderp.opencfmoto.aa.proto.WifiStartRequest)
      WifiStartRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WifiStartRequest.newBuilder() to construct.
    private WifiStartRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WifiStartRequest() {
      ipAddress_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WifiStartRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.zanderp.opencfmoto.aa.proto.Wireless.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiStartRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.zanderp.opencfmoto.aa.proto.Wireless.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiStartRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest.class, dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest.Builder.class);
    }

    private int bitField0_;
    public static final int IP_ADDRESS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object ipAddress_ = "";
    /**
     * <code>required string ip_address = 1;</code>
     * @return Whether the ipAddress field is set.
     */
    @java.lang.Override
    public boolean hasIpAddress() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string ip_address = 1;</code>
     * @return The ipAddress.
     */
    @java.lang.Override
    public java.lang.String getIpAddress() {
      java.lang.Object ref = ipAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ipAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ip_address = 1;</code>
     * @return The bytes for ipAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIpAddressBytes() {
      java.lang.Object ref = ipAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_ = 0;
    /**
     * <code>required int32 port = 2;</code>
     * @return Whether the port field is set.
     */
    @java.lang.Override
    public boolean hasPort() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 port = 2;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private int status_ = 0;
    /**
     * <code>optional int32 status = 3;</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override
    public boolean hasStatus() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 status = 3;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIpAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ipAddress_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, port_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, status_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ipAddress_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest)) {
        return super.equals(obj);
      }
      dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest other = (dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest) obj;

      if (hasIpAddress() != other.hasIpAddress()) return false;
      if (hasIpAddress()) {
        if (!getIpAddress()
            .equals(other.getIpAddress())) return false;
      }
      if (hasPort() != other.hasPort()) return false;
      if (hasPort()) {
        if (getPort()
            != other.getPort()) return false;
      }
      if (hasStatus() != other.hasStatus()) return false;
      if (hasStatus()) {
        if (getStatus()
            != other.getStatus()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasIpAddress()) {
        hash = (37 * hash) + IP_ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getIpAddress().hashCode();
      }
      if (hasPort()) {
        hash = (37 * hash) + PORT_FIELD_NUMBER;
        hash = (53 * hash) + getPort();
      }
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + getStatus();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dev.zanderp.opencfmoto.aa.proto.WifiStartRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dev.zanderp.opencfmoto.aa.proto.WifiStartRequest)
        dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.zanderp.opencfmoto.aa.proto.Wireless.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiStartRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.zanderp.opencfmoto.aa.proto.Wireless.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiStartRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest.class, dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest.Builder.class);
      }

      // Construct using dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        ipAddress_ = "";
        port_ = 0;
        status_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.zanderp.opencfmoto.aa.proto.Wireless.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiStartRequest_descriptor;
      }

      @java.lang.Override
      public dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest getDefaultInstanceForType() {
        return dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest.getDefaultInstance();
      }

      @java.lang.Override
      public dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest build() {
        dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest buildPartial() {
        dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest result = new dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.ipAddress_ = ipAddress_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.port_ = port_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.status_ = status_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest) {
          return mergeFrom((dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest other) {
        if (other == dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest.getDefaultInstance()) return this;
        if (other.hasIpAddress()) {
          ipAddress_ = other.ipAddress_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasIpAddress()) {
          return false;
        }
        if (!hasPort()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                ipAddress_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                port_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                status_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object ipAddress_ = "";
      /**
       * <code>required string ip_address = 1;</code>
       * @return Whether the ipAddress field is set.
       */
      public boolean hasIpAddress() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string ip_address = 1;</code>
       * @return The ipAddress.
       */
      public java.lang.String getIpAddress() {
        java.lang.Object ref = ipAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ipAddress_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ip_address = 1;</code>
       * @return The bytes for ipAddress.
       */
      public com.google.protobuf.ByteString
          getIpAddressBytes() {
        java.lang.Object ref = ipAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ip_address = 1;</code>
       * @param value The ipAddress to set.
       * @return This builder for chaining.
       */
      public Builder setIpAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ipAddress_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required string ip_address = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIpAddress() {
        ipAddress_ = getDefaultInstance().getIpAddress();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>required string ip_address = 1;</code>
       * @param value The bytes for ipAddress to set.
       * @return This builder for chaining.
       */
      public Builder setIpAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ipAddress_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>required int32 port = 2;</code>
       * @return Whether the port field is set.
       */
      @java.lang.Override
      public boolean hasPort() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 port = 2;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return port_;
      }
      /**
       * <code>required int32 port = 2;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {

        port_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 port = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>optional int32 status = 3;</code>
       * @return Whether the status field is set.
       */
      @java.lang.Override
      public boolean hasStatus() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 status = 3;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return status_;
      }
      /**
       * <code>optional int32 status = 3;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {

        status_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 status = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dev.zanderp.opencfmoto.aa.proto.WifiStartRequest)
    }

    // @@protoc_insertion_point(class_scope:dev.zanderp.opencfmoto.aa.proto.WifiStartRequest)
    private static final dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest();
    }

    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<WifiStartRequest>
        PARSER = new com.google.protobuf.AbstractParser<WifiStartRequest>() {
      @java.lang.Override
      public WifiStartRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<WifiStartRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WifiStartRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.zanderp.opencfmoto.aa.proto.Wireless.WifiStartRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WifiInfoResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dev.zanderp.opencfmoto.aa.proto.WifiInfoResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string ssid = 1;</code>
     * @return Whether the ssid field is set.
     */
    boolean hasSsid();
    /**
     * <code>required string ssid = 1;</code>
     * @return The ssid.
     */
    java.lang.String getSsid();
    /**
     * <code>required string ssid = 1;</code>
     * @return The bytes for ssid.
     */
    com.google.protobuf.ByteString
        getSsidBytes();

    /**
     * <code>required string key = 2;</code>
     * @return Whether the key field is set.
     */
    boolean hasKey();
    /**
     * <code>required string key = 2;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 2;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>required string bssid = 3;</code>
     * @return Whether the bssid field is set.
     */
    boolean hasBssid();
    /**
     * <code>required string bssid = 3;</code>
     * @return The bssid.
     */
    java.lang.String getBssid();
    /**
     * <code>required string bssid = 3;</code>
     * @return The bytes for bssid.
     */
    com.google.protobuf.ByteString
        getBssidBytes();

    /**
     * <code>required .dev.zanderp.opencfmoto.aa.proto.SecurityMode security_mode = 4;</code>
     * @return Whether the securityMode field is set.
     */
    boolean hasSecurityMode();
    /**
     * <code>required .dev.zanderp.opencfmoto.aa.proto.SecurityMode security_mode = 4;</code>
     * @return The securityMode.
     */
    dev.zanderp.opencfmoto.aa.proto.Wireless.SecurityMode getSecurityMode();

    /**
     * <code>required .dev.zanderp.opencfmoto.aa.proto.AccessPointType access_point_type = 5;</code>
     * @return Whether the accessPointType field is set.
     */
    boolean hasAccessPointType();
    /**
     * <code>required .dev.zanderp.opencfmoto.aa.proto.AccessPointType access_point_type = 5;</code>
     * @return The accessPointType.
     */
    dev.zanderp.opencfmoto.aa.proto.Wireless.AccessPointType getAccessPointType();
  }
  /**
   * Protobuf type {@code dev.zanderp.opencfmoto.aa.proto.WifiInfoResponse}
   */
  public static final class WifiInfoResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dev.zanderp.opencfmoto.aa.proto.WifiInfoResponse)
      WifiInfoResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WifiInfoResponse.newBuilder() to construct.
    private WifiInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WifiInfoResponse() {
      ssid_ = "";
      key_ = "";
      bssid_ = "";
      securityMode_ = 0;
      accessPointType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WifiInfoResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.zanderp.opencfmoto.aa.proto.Wireless.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiInfoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.zanderp.opencfmoto.aa.proto.Wireless.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse.class, dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse.Builder.class);
    }

    private int bitField0_;
    public static final int SSID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object ssid_ = "";
    /**
     * <code>required string ssid = 1;</code>
     * @return Whether the ssid field is set.
     */
    @java.lang.Override
    public boolean hasSsid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string ssid = 1;</code>
     * @return The ssid.
     */
    @java.lang.Override
    public java.lang.String getSsid() {
      java.lang.Object ref = ssid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ssid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string ssid = 1;</code>
     * @return The bytes for ssid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSsidBytes() {
      java.lang.Object ref = ssid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ssid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object key_ = "";
    /**
     * <code>required string key = 2;</code>
     * @return Whether the key field is set.
     */
    @java.lang.Override
    public boolean hasKey() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string key = 2;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 2;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BSSID_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object bssid_ = "";
    /**
     * <code>required string bssid = 3;</code>
     * @return Whether the bssid field is set.
     */
    @java.lang.Override
    public boolean hasBssid() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string bssid = 3;</code>
     * @return The bssid.
     */
    @java.lang.Override
    public java.lang.String getBssid() {
      java.lang.Object ref = bssid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bssid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string bssid = 3;</code>
     * @return The bytes for bssid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBssidBytes() {
      java.lang.Object ref = bssid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bssid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SECURITY_MODE_FIELD_NUMBER = 4;
    private int securityMode_ = 0;
    /**
     * <code>required .dev.zanderp.opencfmoto.aa.proto.SecurityMode security_mode = 4;</code>
     * @return Whether the securityMode field is set.
     */
    @java.lang.Override public boolean hasSecurityMode() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required .dev.zanderp.opencfmoto.aa.proto.SecurityMode security_mode = 4;</code>
     * @return The securityMode.
     */
    @java.lang.Override public dev.zanderp.opencfmoto.aa.proto.Wireless.SecurityMode getSecurityMode() {
      dev.zanderp.opencfmoto.aa.proto.Wireless.SecurityMode result = dev.zanderp.opencfmoto.aa.proto.Wireless.SecurityMode.forNumber(securityMode_);
      return result == null ? dev.zanderp.opencfmoto.aa.proto.Wireless.SecurityMode.UNKNOWN_SECURITY_MODE : result;
    }

    public static final int ACCESS_POINT_TYPE_FIELD_NUMBER = 5;
    private int accessPointType_ = 0;
    /**
     * <code>required .dev.zanderp.opencfmoto.aa.proto.AccessPointType access_point_type = 5;</code>
     * @return Whether the accessPointType field is set.
     */
    @java.lang.Override public boolean hasAccessPointType() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required .dev.zanderp.opencfmoto.aa.proto.AccessPointType access_point_type = 5;</code>
     * @return The accessPointType.
     */
    @java.lang.Override public dev.zanderp.opencfmoto.aa.proto.Wireless.AccessPointType getAccessPointType() {
      dev.zanderp.opencfmoto.aa.proto.Wireless.AccessPointType result = dev.zanderp.opencfmoto.aa.proto.Wireless.AccessPointType.forNumber(accessPointType_);
      return result == null ? dev.zanderp.opencfmoto.aa.proto.Wireless.AccessPointType.STATIC : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSsid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBssid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSecurityMode()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccessPointType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ssid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, key_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, bssid_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeEnum(4, securityMode_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeEnum(5, accessPointType_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ssid_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, key_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, bssid_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, securityMode_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, accessPointType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse)) {
        return super.equals(obj);
      }
      dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse other = (dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse) obj;

      if (hasSsid() != other.hasSsid()) return false;
      if (hasSsid()) {
        if (!getSsid()
            .equals(other.getSsid())) return false;
      }
      if (hasKey() != other.hasKey()) return false;
      if (hasKey()) {
        if (!getKey()
            .equals(other.getKey())) return false;
      }
      if (hasBssid() != other.hasBssid()) return false;
      if (hasBssid()) {
        if (!getBssid()
            .equals(other.getBssid())) return false;
      }
      if (hasSecurityMode() != other.hasSecurityMode()) return false;
      if (hasSecurityMode()) {
        if (securityMode_ != other.securityMode_) return false;
      }
      if (hasAccessPointType() != other.hasAccessPointType()) return false;
      if (hasAccessPointType()) {
        if (accessPointType_ != other.accessPointType_) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSsid()) {
        hash = (37 * hash) + SSID_FIELD_NUMBER;
        hash = (53 * hash) + getSsid().hashCode();
      }
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
      }
      if (hasBssid()) {
        hash = (37 * hash) + BSSID_FIELD_NUMBER;
        hash = (53 * hash) + getBssid().hashCode();
      }
      if (hasSecurityMode()) {
        hash = (37 * hash) + SECURITY_MODE_FIELD_NUMBER;
        hash = (53 * hash) + securityMode_;
      }
      if (hasAccessPointType()) {
        hash = (37 * hash) + ACCESS_POINT_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + accessPointType_;
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dev.zanderp.opencfmoto.aa.proto.WifiInfoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dev.zanderp.opencfmoto.aa.proto.WifiInfoResponse)
        dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.zanderp.opencfmoto.aa.proto.Wireless.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiInfoResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.zanderp.opencfmoto.aa.proto.Wireless.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiInfoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse.class, dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse.Builder.class);
      }

      // Construct using dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        ssid_ = "";
        key_ = "";
        bssid_ = "";
        securityMode_ = 0;
        accessPointType_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.zanderp.opencfmoto.aa.proto.Wireless.internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiInfoResponse_descriptor;
      }

      @java.lang.Override
      public dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse getDefaultInstanceForType() {
        return dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse.getDefaultInstance();
      }

      @java.lang.Override
      public dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse build() {
        dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse buildPartial() {
        dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse result = new dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.ssid_ = ssid_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.key_ = key_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.bssid_ = bssid_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.securityMode_ = securityMode_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.accessPointType_ = accessPointType_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse) {
          return mergeFrom((dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse other) {
        if (other == dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse.getDefaultInstance()) return this;
        if (other.hasSsid()) {
          ssid_ = other.ssid_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasKey()) {
          key_ = other.key_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasBssid()) {
          bssid_ = other.bssid_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasSecurityMode()) {
          setSecurityMode(other.getSecurityMode());
        }
        if (other.hasAccessPointType()) {
          setAccessPointType(other.getAccessPointType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSsid()) {
          return false;
        }
        if (!hasKey()) {
          return false;
        }
        if (!hasBssid()) {
          return false;
        }
        if (!hasSecurityMode()) {
          return false;
        }
        if (!hasAccessPointType()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                ssid_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                key_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                bssid_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                int tmpRaw = input.readEnum();
                dev.zanderp.opencfmoto.aa.proto.Wireless.SecurityMode tmpValue =
                    dev.zanderp.opencfmoto.aa.proto.Wireless.SecurityMode.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(4, tmpRaw);
                } else {
                  securityMode_ = tmpRaw;
                  bitField0_ |= 0x00000008;
                }
                break;
              } // case 32
              case 40: {
                int tmpRaw = input.readEnum();
                dev.zanderp.opencfmoto.aa.proto.Wireless.AccessPointType tmpValue =
                    dev.zanderp.opencfmoto.aa.proto.Wireless.AccessPointType.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(5, tmpRaw);
                } else {
                  accessPointType_ = tmpRaw;
                  bitField0_ |= 0x00000010;
                }
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object ssid_ = "";
      /**
       * <code>required string ssid = 1;</code>
       * @return Whether the ssid field is set.
       */
      public boolean hasSsid() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string ssid = 1;</code>
       * @return The ssid.
       */
      public java.lang.String getSsid() {
        java.lang.Object ref = ssid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ssid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string ssid = 1;</code>
       * @return The bytes for ssid.
       */
      public com.google.protobuf.ByteString
          getSsidBytes() {
        java.lang.Object ref = ssid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ssid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string ssid = 1;</code>
       * @param value The ssid to set.
       * @return This builder for chaining.
       */
      public Builder setSsid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ssid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required string ssid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSsid() {
        ssid_ = getDefaultInstance().getSsid();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>required string ssid = 1;</code>
       * @param value The bytes for ssid to set.
       * @return This builder for chaining.
       */
      public Builder setSsidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ssid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 2;</code>
       * @return Whether the key field is set.
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string key = 2;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 2;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 2;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        key_ = getDefaultInstance().getKey();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 2;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object bssid_ = "";
      /**
       * <code>required string bssid = 3;</code>
       * @return Whether the bssid field is set.
       */
      public boolean hasBssid() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string bssid = 3;</code>
       * @return The bssid.
       */
      public java.lang.String getBssid() {
        java.lang.Object ref = bssid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            bssid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string bssid = 3;</code>
       * @return The bytes for bssid.
       */
      public com.google.protobuf.ByteString
          getBssidBytes() {
        java.lang.Object ref = bssid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bssid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string bssid = 3;</code>
       * @param value The bssid to set.
       * @return This builder for chaining.
       */
      public Builder setBssid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        bssid_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>required string bssid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBssid() {
        bssid_ = getDefaultInstance().getBssid();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>required string bssid = 3;</code>
       * @param value The bytes for bssid to set.
       * @return This builder for chaining.
       */
      public Builder setBssidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        bssid_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int securityMode_ = 0;
      /**
       * <code>required .dev.zanderp.opencfmoto.aa.proto.SecurityMode security_mode = 4;</code>
       * @return Whether the securityMode field is set.
       */
      @java.lang.Override public boolean hasSecurityMode() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required .dev.zanderp.opencfmoto.aa.proto.SecurityMode security_mode = 4;</code>
       * @return The securityMode.
       */
      @java.lang.Override
      public dev.zanderp.opencfmoto.aa.proto.Wireless.SecurityMode getSecurityMode() {
        dev.zanderp.opencfmoto.aa.proto.Wireless.SecurityMode result = dev.zanderp.opencfmoto.aa.proto.Wireless.SecurityMode.forNumber(securityMode_);
        return result == null ? dev.zanderp.opencfmoto.aa.proto.Wireless.SecurityMode.UNKNOWN_SECURITY_MODE : result;
      }
      /**
       * <code>required .dev.zanderp.opencfmoto.aa.proto.SecurityMode security_mode = 4;</code>
       * @param value The securityMode to set.
       * @return This builder for chaining.
       */
      public Builder setSecurityMode(dev.zanderp.opencfmoto.aa.proto.Wireless.SecurityMode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        securityMode_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .dev.zanderp.opencfmoto.aa.proto.SecurityMode security_mode = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecurityMode() {
        bitField0_ = (bitField0_ & ~0x00000008);
        securityMode_ = 0;
        onChanged();
        return this;
      }

      private int accessPointType_ = 0;
      /**
       * <code>required .dev.zanderp.opencfmoto.aa.proto.AccessPointType access_point_type = 5;</code>
       * @return Whether the accessPointType field is set.
       */
      @java.lang.Override public boolean hasAccessPointType() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required .dev.zanderp.opencfmoto.aa.proto.AccessPointType access_point_type = 5;</code>
       * @return The accessPointType.
       */
      @java.lang.Override
      public dev.zanderp.opencfmoto.aa.proto.Wireless.AccessPointType getAccessPointType() {
        dev.zanderp.opencfmoto.aa.proto.Wireless.AccessPointType result = dev.zanderp.opencfmoto.aa.proto.Wireless.AccessPointType.forNumber(accessPointType_);
        return result == null ? dev.zanderp.opencfmoto.aa.proto.Wireless.AccessPointType.STATIC : result;
      }
      /**
       * <code>required .dev.zanderp.opencfmoto.aa.proto.AccessPointType access_point_type = 5;</code>
       * @param value The accessPointType to set.
       * @return This builder for chaining.
       */
      public Builder setAccessPointType(dev.zanderp.opencfmoto.aa.proto.Wireless.AccessPointType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000010;
        accessPointType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .dev.zanderp.opencfmoto.aa.proto.AccessPointType access_point_type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearAccessPointType() {
        bitField0_ = (bitField0_ & ~0x00000010);
        accessPointType_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dev.zanderp.opencfmoto.aa.proto.WifiInfoResponse)
    }

    // @@protoc_insertion_point(class_scope:dev.zanderp.opencfmoto.aa.proto.WifiInfoResponse)
    private static final dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse();
    }

    public static dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<WifiInfoResponse>
        PARSER = new com.google.protobuf.AbstractParser<WifiInfoResponse>() {
      @java.lang.Override
      public WifiInfoResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<WifiInfoResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WifiInfoResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.zanderp.opencfmoto.aa.proto.Wireless.WifiInfoResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiStartRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiStartRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiInfoResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiInfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016wireless.proto\0221com.andrerinas.headuni" +
      "trevived.aap.protocol.proto\"D\n\020WifiStart" +
      "Request\022\022\n\nip_address\030\001 \002(\t\022\014\n\004port\030\002 \002(" +
      "\005\022\016\n\006status\030\003 \001(\005\"\363\001\n\020WifiInfoResponse\022\014" +
      "\n\004ssid\030\001 \002(\t\022\013\n\003key\030\002 \002(\t\022\r\n\005bssid\030\003 \002(\t" +
      "\022V\n\rsecurity_mode\030\004 \002(\0162?.com.andrerinas" +
      ".headunitrevived.aap.protocol.proto.Secu" +
      "rityMode\022]\n\021access_point_type\030\005 \002(\0162B.co" +
      "m.andrerinas.headunitrevived.aap.protoco" +
      "l.proto.AccessPointType**\n\017AccessPointTy" +
      "pe\022\n\n\006STATIC\020\000\022\013\n\007DYNAMIC\020\001*\312\001\n\014Security" +
      "Mode\022\031\n\025UNKNOWN_SECURITY_MODE\020\000\022\010\n\004OPEN\020" +
      "\001\022\n\n\006WEP_64\020\002\022\013\n\007WEP_128\020\003\022\020\n\014WPA_PERSON" +
      "AL\020\004\022\021\n\rWPA2_PERSONAL\020\010\022\025\n\021WPA_WPA2_PERS" +
      "ONAL\020\014\022\022\n\016WPA_ENTERPRISE\020\024\022\023\n\017WPA2_ENTER" +
      "PRISE\020\030\022\027\n\023WPA_WPA2_ENTERPRISE\020\034"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiStartRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiStartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiStartRequest_descriptor,
        new java.lang.String[] { "IpAddress", "Port", "Status", });
    internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_andrerinas_headunitrevived_aap_protocol_proto_WifiInfoResponse_descriptor,
        new java.lang.String[] { "Ssid", "Key", "Bssid", "SecurityMode", "AccessPointType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
